// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: init.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAllocation = `-- name: CreateAllocation :one
INSERT INTO doc.allocations (doc_line_id, balance_id, qty_allocated, qty_picked, created_at)
VALUES ($1, $2, $3, 0, NOW())
RETURNING id, doc_line_id, balance_id, qty_allocated, qty_picked, created_at
`

type CreateAllocationParams struct {
	DocLineID    int64          `json:"doc_line_id"`
	BalanceID    int64          `json:"balance_id"`
	QtyAllocated pgtype.Numeric `json:"qty_allocated"`
}

func (q *Queries) CreateAllocation(ctx context.Context, arg CreateAllocationParams) (DocAllocations, error) {
	row := q.db.QueryRow(ctx, createAllocation, arg.DocLineID, arg.BalanceID, arg.QtyAllocated)
	var i DocAllocations
	err := row.Scan(
		&i.ID,
		&i.DocLineID,
		&i.BalanceID,
		&i.QtyAllocated,
		&i.QtyPicked,
		&i.CreatedAt,
	)
	return i, err
}

const createBatch = `-- name: CreateBatch :one
INSERT INTO master.batches (item_id, batch_no, mfg_date, expiry_date)
VALUES ($1, $2, $3, $4)
RETURNING id, item_id, batch_no, mfg_date, expiry_date
`

type CreateBatchParams struct {
	ItemID     int64       `json:"item_id"`
	BatchNo    string      `json:"batch_no"`
	MfgDate    pgtype.Date `json:"mfg_date"`
	ExpiryDate pgtype.Date `json:"expiry_date"`
}

func (q *Queries) CreateBatch(ctx context.Context, arg CreateBatchParams) (MasterBatches, error) {
	row := q.db.QueryRow(ctx, createBatch,
		arg.ItemID,
		arg.BatchNo,
		arg.MfgDate,
		arg.ExpiryDate,
	)
	var i MasterBatches
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.BatchNo,
		&i.MfgDate,
		&i.ExpiryDate,
	)
	return i, err
}

const createCategory = `-- name: CreateCategory :one

INSERT INTO master.categories (code, name, is_active)
VALUES ($1, $2, $3)
RETURNING id, code, name, is_active
`

type CreateCategoryParams struct {
	Code     string `json:"code"`
	Name     string `json:"name"`
	IsActive bool   `json:"is_active"`
}

// ============ CATEGORIES ============
func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (MasterCategories, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Code, arg.Name, arg.IsActive)
	var i MasterCategories
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.IsActive,
	)
	return i, err
}

const createCountLine = `-- name: CreateCountLine :one
INSERT INTO doc.count_lines (document_id, item_id, location_id, batch_id, qty_system)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, document_id, item_id, location_id, batch_id, qty_system, qty_counted, variance, reason_code, counted_by, counted_at
`

type CreateCountLineParams struct {
	DocumentID int64          `json:"document_id"`
	ItemID     int64          `json:"item_id"`
	LocationID int64          `json:"location_id"`
	BatchID    pgtype.Int8    `json:"batch_id"`
	QtySystem  pgtype.Numeric `json:"qty_system"`
}

func (q *Queries) CreateCountLine(ctx context.Context, arg CreateCountLineParams) (DocCountLines, error) {
	row := q.db.QueryRow(ctx, createCountLine,
		arg.DocumentID,
		arg.ItemID,
		arg.LocationID,
		arg.BatchID,
		arg.QtySystem,
	)
	var i DocCountLines
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.ItemID,
		&i.LocationID,
		&i.BatchID,
		&i.QtySystem,
		&i.QtyCounted,
		&i.Variance,
		&i.ReasonCode,
		&i.CountedBy,
		&i.CountedAt,
	)
	return i, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO doc.documents (doc_no, doc_type, doc_date, status, warehouse_id, dest_warehouse_id, ref_doc_id, partner_id, reason_code, idempotency_key, notes, created_by)
VALUES ($1, $2::doc.doc_type, $3, $4::doc.doc_status, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, public_id, doc_no, doc_type, doc_date, status, warehouse_id, dest_warehouse_id, ref_doc_id, partner_id, reason_code, idempotency_key, notes, created_by, created_at
`

type CreateDocumentParams struct {
	DocNo           string      `json:"doc_no"`
	Column2         interface{} `json:"column_2"`
	DocDate         pgtype.Date `json:"doc_date"`
	Column4         interface{} `json:"column_4"`
	WarehouseID     int64       `json:"warehouse_id"`
	DestWarehouseID pgtype.Int8 `json:"dest_warehouse_id"`
	RefDocID        pgtype.Int8 `json:"ref_doc_id"`
	PartnerID       pgtype.Int8 `json:"partner_id"`
	ReasonCode      pgtype.Text `json:"reason_code"`
	IdempotencyKey  pgtype.Text `json:"idempotency_key"`
	Notes           pgtype.Text `json:"notes"`
	CreatedBy       int64       `json:"created_by"`
}

type CreateDocumentRow struct {
	ID              int64              `json:"id"`
	PublicID        pgtype.UUID        `json:"public_id"`
	DocNo           string             `json:"doc_no"`
	DocType         interface{}        `json:"doc_type"`
	DocDate         pgtype.Date        `json:"doc_date"`
	Status          interface{}        `json:"status"`
	WarehouseID     int64              `json:"warehouse_id"`
	DestWarehouseID pgtype.Int8        `json:"dest_warehouse_id"`
	RefDocID        pgtype.Int8        `json:"ref_doc_id"`
	PartnerID       pgtype.Int8        `json:"partner_id"`
	ReasonCode      pgtype.Text        `json:"reason_code"`
	IdempotencyKey  pgtype.Text        `json:"idempotency_key"`
	Notes           pgtype.Text        `json:"notes"`
	CreatedBy       int64              `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (CreateDocumentRow, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.DocNo,
		arg.Column2,
		arg.DocDate,
		arg.Column4,
		arg.WarehouseID,
		arg.DestWarehouseID,
		arg.RefDocID,
		arg.PartnerID,
		arg.ReasonCode,
		arg.IdempotencyKey,
		arg.Notes,
		arg.CreatedBy,
	)
	var i CreateDocumentRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.DocNo,
		&i.DocType,
		&i.DocDate,
		&i.Status,
		&i.WarehouseID,
		&i.DestWarehouseID,
		&i.RefDocID,
		&i.PartnerID,
		&i.ReasonCode,
		&i.IdempotencyKey,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createDocumentLine = `-- name: CreateDocumentLine :one
INSERT INTO doc.document_lines (document_id, line_no, item_id, uom, conv_factor, qty_request, qty_processed, batch_id, location_id, status, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10::inv.stock_status, $11)
RETURNING id, document_id, line_no, item_id, uom, conv_factor, qty_request, qty_processed, batch_id, location_id, status, notes
`

type CreateDocumentLineParams struct {
	DocumentID   int64          `json:"document_id"`
	LineNo       int16          `json:"line_no"`
	ItemID       int64          `json:"item_id"`
	Uom          string         `json:"uom"`
	ConvFactor   pgtype.Numeric `json:"conv_factor"`
	QtyRequest   pgtype.Numeric `json:"qty_request"`
	QtyProcessed pgtype.Numeric `json:"qty_processed"`
	BatchID      pgtype.Int8    `json:"batch_id"`
	LocationID   pgtype.Int8    `json:"location_id"`
	Column10     interface{}    `json:"column_10"`
	Notes        pgtype.Text    `json:"notes"`
}

func (q *Queries) CreateDocumentLine(ctx context.Context, arg CreateDocumentLineParams) (DocDocumentLines, error) {
	row := q.db.QueryRow(ctx, createDocumentLine,
		arg.DocumentID,
		arg.LineNo,
		arg.ItemID,
		arg.Uom,
		arg.ConvFactor,
		arg.QtyRequest,
		arg.QtyProcessed,
		arg.BatchID,
		arg.LocationID,
		arg.Column10,
		arg.Notes,
	)
	var i DocDocumentLines
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.LineNo,
		&i.ItemID,
		&i.Uom,
		&i.ConvFactor,
		&i.QtyRequest,
		&i.QtyProcessed,
		&i.BatchID,
		&i.LocationID,
		&i.Status,
		&i.Notes,
	)
	return i, err
}

const createItem = `-- name: CreateItem :one

INSERT INTO master.items (
    sku, name, category_id, base_uom, is_batch, is_expiry, is_serial,
    min_qty, max_qty, safety_stock, lead_time_days, abc_class, is_active, created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, public_id, sku, name, category_id, base_uom, is_batch, is_expiry, is_serial, min_qty, max_qty, safety_stock, lead_time_days, abc_class, is_active, created_at, created_by
`

type CreateItemParams struct {
	Sku          string         `json:"sku"`
	Name         string         `json:"name"`
	CategoryID   pgtype.Int8    `json:"category_id"`
	BaseUom      string         `json:"base_uom"`
	IsBatch      bool           `json:"is_batch"`
	IsExpiry     bool           `json:"is_expiry"`
	IsSerial     bool           `json:"is_serial"`
	MinQty       pgtype.Numeric `json:"min_qty"`
	MaxQty       pgtype.Numeric `json:"max_qty"`
	SafetyStock  pgtype.Numeric `json:"safety_stock"`
	LeadTimeDays int16          `json:"lead_time_days"`
	AbcClass     pgtype.Text    `json:"abc_class"`
	IsActive     bool           `json:"is_active"`
	CreatedBy    int64          `json:"created_by"`
}

type CreateItemRow struct {
	ID           int64              `json:"id"`
	PublicID     pgtype.UUID        `json:"public_id"`
	Sku          string             `json:"sku"`
	Name         string             `json:"name"`
	CategoryID   pgtype.Int8        `json:"category_id"`
	BaseUom      string             `json:"base_uom"`
	IsBatch      bool               `json:"is_batch"`
	IsExpiry     bool               `json:"is_expiry"`
	IsSerial     bool               `json:"is_serial"`
	MinQty       pgtype.Numeric     `json:"min_qty"`
	MaxQty       pgtype.Numeric     `json:"max_qty"`
	SafetyStock  pgtype.Numeric     `json:"safety_stock"`
	LeadTimeDays int16              `json:"lead_time_days"`
	AbcClass     pgtype.Text        `json:"abc_class"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CreatedBy    int64              `json:"created_by"`
}

// ============ ITEMS & UOMS ============
func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (CreateItemRow, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.Sku,
		arg.Name,
		arg.CategoryID,
		arg.BaseUom,
		arg.IsBatch,
		arg.IsExpiry,
		arg.IsSerial,
		arg.MinQty,
		arg.MaxQty,
		arg.SafetyStock,
		arg.LeadTimeDays,
		arg.AbcClass,
		arg.IsActive,
		arg.CreatedBy,
	)
	var i CreateItemRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Sku,
		&i.Name,
		&i.CategoryID,
		&i.BaseUom,
		&i.IsBatch,
		&i.IsExpiry,
		&i.IsSerial,
		&i.MinQty,
		&i.MaxQty,
		&i.SafetyStock,
		&i.LeadTimeDays,
		&i.AbcClass,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const createItemUoM = `-- name: CreateItemUoM :one
INSERT INTO master.item_uoms (item_id, uom, conv_factor, barcode)
VALUES ($1, $2, $3, $4)
RETURNING id, item_id, uom, conv_factor, barcode
`

type CreateItemUoMParams struct {
	ItemID     int64          `json:"item_id"`
	Uom        string         `json:"uom"`
	ConvFactor pgtype.Numeric `json:"conv_factor"`
	Barcode    pgtype.Text    `json:"barcode"`
}

func (q *Queries) CreateItemUoM(ctx context.Context, arg CreateItemUoMParams) (MasterItemUoms, error) {
	row := q.db.QueryRow(ctx, createItemUoM,
		arg.ItemID,
		arg.Uom,
		arg.ConvFactor,
		arg.Barcode,
	)
	var i MasterItemUoms
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Uom,
		&i.ConvFactor,
		&i.Barcode,
	)
	return i, err
}

const createLocation = `-- name: CreateLocation :one

INSERT INTO master.locations (warehouse_id, code, zone, rack, level, loc_type, pick_seq, capacity, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, warehouse_id, code, zone, rack, level, loc_type, pick_seq, capacity, is_active
`

type CreateLocationParams struct {
	WarehouseID int64          `json:"warehouse_id"`
	Code        string         `json:"code"`
	Zone        pgtype.Text    `json:"zone"`
	Rack        pgtype.Text    `json:"rack"`
	Level       pgtype.Text    `json:"level"`
	LocType     interface{}    `json:"loc_type"`
	PickSeq     pgtype.Int4    `json:"pick_seq"`
	Capacity    pgtype.Numeric `json:"capacity"`
	IsActive    bool           `json:"is_active"`
}

// ============ LOCATIONS ============
func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (MasterLocations, error) {
	row := q.db.QueryRow(ctx, createLocation,
		arg.WarehouseID,
		arg.Code,
		arg.Zone,
		arg.Rack,
		arg.Level,
		arg.LocType,
		arg.PickSeq,
		arg.Capacity,
		arg.IsActive,
	)
	var i MasterLocations
	err := row.Scan(
		&i.ID,
		&i.WarehouseID,
		&i.Code,
		&i.Zone,
		&i.Rack,
		&i.Level,
		&i.LocType,
		&i.PickSeq,
		&i.Capacity,
		&i.IsActive,
	)
	return i, err
}

const createPartner = `-- name: CreatePartner :one

INSERT INTO master.partners (code, partner_type, name, address, contact_name, contact_phone, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, code, partner_type, name, address, contact_name, contact_phone, is_active
`

type CreatePartnerParams struct {
	Code         string      `json:"code"`
	PartnerType  string      `json:"partner_type"`
	Name         string      `json:"name"`
	Address      pgtype.Text `json:"address"`
	ContactName  pgtype.Text `json:"contact_name"`
	ContactPhone pgtype.Text `json:"contact_phone"`
	IsActive     bool        `json:"is_active"`
}

// ============ PARTNERS ============
func (q *Queries) CreatePartner(ctx context.Context, arg CreatePartnerParams) (MasterPartners, error) {
	row := q.db.QueryRow(ctx, createPartner,
		arg.Code,
		arg.PartnerType,
		arg.Name,
		arg.Address,
		arg.ContactName,
		arg.ContactPhone,
		arg.IsActive,
	)
	var i MasterPartners
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.PartnerType,
		&i.Name,
		&i.Address,
		&i.ContactName,
		&i.ContactPhone,
		&i.IsActive,
	)
	return i, err
}

const createStockMovement = `-- name: CreateStockMovement :one
INSERT INTO inv.stock_movements (item_id, location_id, batch_id, status, movement_type, qty, qty_after, doc_line_id, doc_no, created_by, moved_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW())
RETURNING id, moved_at, qty_after
`

type CreateStockMovementParams struct {
	ItemID       int64          `json:"item_id"`
	LocationID   int64          `json:"location_id"`
	BatchID      pgtype.Int8    `json:"batch_id"`
	Status       interface{}    `json:"status"`
	MovementType interface{}    `json:"movement_type"`
	Qty          pgtype.Numeric `json:"qty"`
	QtyAfter     pgtype.Numeric `json:"qty_after"`
	DocLineID    pgtype.Int8    `json:"doc_line_id"`
	DocNo        string         `json:"doc_no"`
	CreatedBy    int64          `json:"created_by"`
}

type CreateStockMovementRow struct {
	ID       int64              `json:"id"`
	MovedAt  pgtype.Timestamptz `json:"moved_at"`
	QtyAfter pgtype.Numeric     `json:"qty_after"`
}

func (q *Queries) CreateStockMovement(ctx context.Context, arg CreateStockMovementParams) (CreateStockMovementRow, error) {
	row := q.db.QueryRow(ctx, createStockMovement,
		arg.ItemID,
		arg.LocationID,
		arg.BatchID,
		arg.Status,
		arg.MovementType,
		arg.Qty,
		arg.QtyAfter,
		arg.DocLineID,
		arg.DocNo,
		arg.CreatedBy,
	)
	var i CreateStockMovementRow
	err := row.Scan(&i.ID, &i.MovedAt, &i.QtyAfter)
	return i, err
}

const createTransferReceipt = `-- name: CreateTransferReceipt :one
INSERT INTO doc.transfer_receipts (document_id, line_id, qty_sent, qty_received, received_by, notes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, document_id, line_id, qty_sent, qty_received, variance, received_by, received_at, notes
`

type CreateTransferReceiptParams struct {
	DocumentID  int64          `json:"document_id"`
	LineID      int64          `json:"line_id"`
	QtySent     pgtype.Numeric `json:"qty_sent"`
	QtyReceived pgtype.Numeric `json:"qty_received"`
	ReceivedBy  int64          `json:"received_by"`
	Notes       pgtype.Text    `json:"notes"`
}

func (q *Queries) CreateTransferReceipt(ctx context.Context, arg CreateTransferReceiptParams) (DocTransferReceipts, error) {
	row := q.db.QueryRow(ctx, createTransferReceipt,
		arg.DocumentID,
		arg.LineID,
		arg.QtySent,
		arg.QtyReceived,
		arg.ReceivedBy,
		arg.Notes,
	)
	var i DocTransferReceipts
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.LineID,
		&i.QtySent,
		&i.QtyReceived,
		&i.Variance,
		&i.ReceivedBy,
		&i.ReceivedAt,
		&i.Notes,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO sec.users (username, email, full_name, password_hash, is_active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, email, full_name, is_active
`

type CreateUserParams struct {
	Username     string      `json:"username"`
	Email        pgtype.Text `json:"email"`
	FullName     string      `json:"full_name"`
	PasswordHash string      `json:"password_hash"`
	IsActive     bool        `json:"is_active"`
}

type CreateUserRow struct {
	ID       int64       `json:"id"`
	Username string      `json:"username"`
	Email    pgtype.Text `json:"email"`
	FullName string      `json:"full_name"`
	IsActive bool        `json:"is_active"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.FullName,
		arg.PasswordHash,
		arg.IsActive,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.IsActive,
	)
	return i, err
}

const createWarehouse = `-- name: CreateWarehouse :one
INSERT INTO master.warehouses (code, name, address, is_active)
VALUES ($1, $2, $3, $4)
RETURNING id, code, name, address, is_active
`

type CreateWarehouseParams struct {
	Code     string      `json:"code"`
	Name     string      `json:"name"`
	Address  pgtype.Text `json:"address"`
	IsActive bool        `json:"is_active"`
}

func (q *Queries) CreateWarehouse(ctx context.Context, arg CreateWarehouseParams) (MasterWarehouses, error) {
	row := q.db.QueryRow(ctx, createWarehouse,
		arg.Code,
		arg.Name,
		arg.Address,
		arg.IsActive,
	)
	var i MasterWarehouses
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Address,
		&i.IsActive,
	)
	return i, err
}

const deleteItemUoMs = `-- name: DeleteItemUoMs :exec
DELETE FROM master.item_uoms
WHERE item_id = $1
`

func (q *Queries) DeleteItemUoMs(ctx context.Context, itemID int64) error {
	_, err := q.db.Exec(ctx, deleteItemUoMs, itemID)
	return err
}

const deleteLocation = `-- name: DeleteLocation :exec
DELETE FROM master.locations
WHERE id = $1
`

func (q *Queries) DeleteLocation(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteLocation, id)
	return err
}

const deletePartner = `-- name: DeletePartner :exec
DELETE FROM master.partners
WHERE id = $1
`

func (q *Queries) DeletePartner(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePartner, id)
	return err
}

const getAllocationCandidateByBalanceID = `-- name: GetAllocationCandidateByBalanceID :one
SELECT b.id AS balance_id, b.item_id, b.location_id, b.batch_id,
       b.qty_onhand, b.qty_reserved,
       l.warehouse_id, l.code AS location_code, l.pick_seq, bt.expiry_date
FROM inv.stock_balances b
JOIN master.locations l ON l.id = b.location_id
LEFT JOIN master.batches bt ON bt.id = b.batch_id
WHERE b.id = $1
  AND l.warehouse_id = $2
  AND b.status = 'available'
  AND (bt.expiry_date IS NULL OR bt.expiry_date > CURRENT_DATE)
FOR UPDATE OF b
`

type GetAllocationCandidateByBalanceIDParams struct {
	ID          int64 `json:"id"`
	WarehouseID int64 `json:"warehouse_id"`
}

type GetAllocationCandidateByBalanceIDRow struct {
	BalanceID    int64          `json:"balance_id"`
	ItemID       int64          `json:"item_id"`
	LocationID   int64          `json:"location_id"`
	BatchID      pgtype.Int8    `json:"batch_id"`
	QtyOnhand    pgtype.Numeric `json:"qty_onhand"`
	QtyReserved  pgtype.Numeric `json:"qty_reserved"`
	WarehouseID  int64          `json:"warehouse_id"`
	LocationCode string         `json:"location_code"`
	PickSeq      pgtype.Int4    `json:"pick_seq"`
	ExpiryDate   pgtype.Date    `json:"expiry_date"`
}

// Manual override target: locks one specific balance (Fase 7.3). Must belong
// to the warehouse, be available, and not be expired.
func (q *Queries) GetAllocationCandidateByBalanceID(ctx context.Context, arg GetAllocationCandidateByBalanceIDParams) (GetAllocationCandidateByBalanceIDRow, error) {
	row := q.db.QueryRow(ctx, getAllocationCandidateByBalanceID, arg.ID, arg.WarehouseID)
	var i GetAllocationCandidateByBalanceIDRow
	err := row.Scan(
		&i.BalanceID,
		&i.ItemID,
		&i.LocationID,
		&i.BatchID,
		&i.QtyOnhand,
		&i.QtyReserved,
		&i.WarehouseID,
		&i.LocationCode,
		&i.PickSeq,
		&i.ExpiryDate,
	)
	return i, err
}

const getBatchByItemAndNo = `-- name: GetBatchByItemAndNo :one
SELECT id, item_id, batch_no, mfg_date, expiry_date
FROM master.batches
WHERE item_id = $1 AND batch_no = $2
LIMIT 1
`

type GetBatchByItemAndNoParams struct {
	ItemID  int64  `json:"item_id"`
	BatchNo string `json:"batch_no"`
}

func (q *Queries) GetBatchByItemAndNo(ctx context.Context, arg GetBatchByItemAndNoParams) (MasterBatches, error) {
	row := q.db.QueryRow(ctx, getBatchByItemAndNo, arg.ItemID, arg.BatchNo)
	var i MasterBatches
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.BatchNo,
		&i.MfgDate,
		&i.ExpiryDate,
	)
	return i, err
}

const getDeliveryByDocument = `-- name: GetDeliveryByDocument :one
SELECT document_id, vehicle_no, driver_name, shipped_at, received_by, received_at, pod_file_url, signature_url
FROM doc.deliveries
WHERE document_id = $1
`

func (q *Queries) GetDeliveryByDocument(ctx context.Context, documentID int64) (DocDeliveries, error) {
	row := q.db.QueryRow(ctx, getDeliveryByDocument, documentID)
	var i DocDeliveries
	err := row.Scan(
		&i.DocumentID,
		&i.VehicleNo,
		&i.DriverName,
		&i.ShippedAt,
		&i.ReceivedBy,
		&i.ReceivedAt,
		&i.PodFileUrl,
		&i.SignatureUrl,
	)
	return i, err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, public_id, doc_no, doc_type, doc_date, status, warehouse_id, dest_warehouse_id, partner_id, ref_doc_id, reason_code, notes, idempotency_key, created_at, created_by, submitted_at, approved_at, approved_by, completed_at, manager_approved_by, manager_approved_at
FROM doc.documents
WHERE id = $1
`

func (q *Queries) GetDocumentByID(ctx context.Context, id int64) (DocDocuments, error) {
	row := q.db.QueryRow(ctx, getDocumentByID, id)
	var i DocDocuments
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.DocNo,
		&i.DocType,
		&i.DocDate,
		&i.Status,
		&i.WarehouseID,
		&i.DestWarehouseID,
		&i.PartnerID,
		&i.RefDocID,
		&i.ReasonCode,
		&i.Notes,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.SubmittedAt,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.CompletedAt,
		&i.ManagerApprovedBy,
		&i.ManagerApprovedAt,
	)
	return i, err
}

const getDocumentByIDempotencyKey = `-- name: GetDocumentByIDempotencyKey :one
SELECT id, public_id, doc_no, doc_type, doc_date, status, warehouse_id, dest_warehouse_id, partner_id, ref_doc_id, reason_code, notes, idempotency_key, created_at, created_by, submitted_at, approved_at, approved_by, completed_at, manager_approved_by, manager_approved_at
FROM doc.documents
WHERE idempotency_key = $1
`

func (q *Queries) GetDocumentByIDempotencyKey(ctx context.Context, idempotencyKey pgtype.Text) (DocDocuments, error) {
	row := q.db.QueryRow(ctx, getDocumentByIDempotencyKey, idempotencyKey)
	var i DocDocuments
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.DocNo,
		&i.DocType,
		&i.DocDate,
		&i.Status,
		&i.WarehouseID,
		&i.DestWarehouseID,
		&i.PartnerID,
		&i.RefDocID,
		&i.ReasonCode,
		&i.Notes,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.SubmittedAt,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.CompletedAt,
		&i.ManagerApprovedBy,
		&i.ManagerApprovedAt,
	)
	return i, err
}

const getItemByBarcode = `-- name: GetItemByBarcode :one
SELECT i.id AS item_id, i.sku, i.base_uom, u.uom, u.conv_factor
FROM master.item_uoms u
JOIN master.items i ON i.id = u.item_id
WHERE u.barcode = $1
LIMIT 1
`

type GetItemByBarcodeRow struct {
	ItemID     int64          `json:"item_id"`
	Sku        string         `json:"sku"`
	BaseUom    string         `json:"base_uom"`
	Uom        string         `json:"uom"`
	ConvFactor pgtype.Numeric `json:"conv_factor"`
}

func (q *Queries) GetItemByBarcode(ctx context.Context, barcode pgtype.Text) (GetItemByBarcodeRow, error) {
	row := q.db.QueryRow(ctx, getItemByBarcode, barcode)
	var i GetItemByBarcodeRow
	err := row.Scan(
		&i.ItemID,
		&i.Sku,
		&i.BaseUom,
		&i.Uom,
		&i.ConvFactor,
	)
	return i, err
}

const getItemByID = `-- name: GetItemByID :one
SELECT id, public_id, sku, name, category_id, base_uom, is_batch, is_expiry, is_serial, min_qty, max_qty, safety_stock, lead_time_days, abc_class, is_active, created_at, created_by, updated_at, updated_by
FROM master.items
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetItemByID(ctx context.Context, id int64) (MasterItems, error) {
	row := q.db.QueryRow(ctx, getItemByID, id)
	var i MasterItems
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Sku,
		&i.Name,
		&i.CategoryID,
		&i.BaseUom,
		&i.IsBatch,
		&i.IsExpiry,
		&i.IsSerial,
		&i.MinQty,
		&i.MaxQty,
		&i.SafetyStock,
		&i.LeadTimeDays,
		&i.AbcClass,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getItemBySKU = `-- name: GetItemBySKU :one
SELECT id, public_id, sku, name, category_id, base_uom, is_batch, is_expiry, is_serial, min_qty, max_qty, safety_stock, lead_time_days, abc_class, is_active, created_at, created_by
FROM master.items
WHERE sku = $1 LIMIT 1
`

type GetItemBySKURow struct {
	ID           int64              `json:"id"`
	PublicID     pgtype.UUID        `json:"public_id"`
	Sku          string             `json:"sku"`
	Name         string             `json:"name"`
	CategoryID   pgtype.Int8        `json:"category_id"`
	BaseUom      string             `json:"base_uom"`
	IsBatch      bool               `json:"is_batch"`
	IsExpiry     bool               `json:"is_expiry"`
	IsSerial     bool               `json:"is_serial"`
	MinQty       pgtype.Numeric     `json:"min_qty"`
	MaxQty       pgtype.Numeric     `json:"max_qty"`
	SafetyStock  pgtype.Numeric     `json:"safety_stock"`
	LeadTimeDays int16              `json:"lead_time_days"`
	AbcClass     pgtype.Text        `json:"abc_class"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CreatedBy    int64              `json:"created_by"`
}

func (q *Queries) GetItemBySKU(ctx context.Context, sku string) (GetItemBySKURow, error) {
	row := q.db.QueryRow(ctx, getItemBySKU, sku)
	var i GetItemBySKURow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Sku,
		&i.Name,
		&i.CategoryID,
		&i.BaseUom,
		&i.IsBatch,
		&i.IsExpiry,
		&i.IsSerial,
		&i.MinQty,
		&i.MaxQty,
		&i.SafetyStock,
		&i.LeadTimeDays,
		&i.AbcClass,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getLastUnitCostByItem = `-- name: GetLastUnitCostByItem :one
SELECT unit_cost
FROM inv.stock_movements
WHERE item_id = $1 AND unit_cost IS NOT NULL
ORDER BY moved_at DESC, id DESC
LIMIT 1
`

// Harga pokok terakhir item untuk menilai selisih opname (M6.4 threshold).
func (q *Queries) GetLastUnitCostByItem(ctx context.Context, itemID int64) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getLastUnitCostByItem, itemID)
	var unit_cost pgtype.Numeric
	err := row.Scan(&unit_cost)
	return unit_cost, err
}

const getLocationByID = `-- name: GetLocationByID :one
SELECT id, warehouse_id, code, zone, rack, level, loc_type, pick_seq, capacity, is_active
FROM master.locations
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetLocationByID(ctx context.Context, id int64) (MasterLocations, error) {
	row := q.db.QueryRow(ctx, getLocationByID, id)
	var i MasterLocations
	err := row.Scan(
		&i.ID,
		&i.WarehouseID,
		&i.Code,
		&i.Zone,
		&i.Rack,
		&i.Level,
		&i.LocType,
		&i.PickSeq,
		&i.Capacity,
		&i.IsActive,
	)
	return i, err
}

const getLocationByWarehouseCode = `-- name: GetLocationByWarehouseCode :one
SELECT id, warehouse_id, code, zone, rack, level, loc_type, pick_seq, capacity, is_active
FROM master.locations
WHERE warehouse_id = $1 AND code = $2 AND is_active = TRUE
LIMIT 1
`

type GetLocationByWarehouseCodeParams struct {
	WarehouseID int64  `json:"warehouse_id"`
	Code        string `json:"code"`
}

func (q *Queries) GetLocationByWarehouseCode(ctx context.Context, arg GetLocationByWarehouseCodeParams) (MasterLocations, error) {
	row := q.db.QueryRow(ctx, getLocationByWarehouseCode, arg.WarehouseID, arg.Code)
	var i MasterLocations
	err := row.Scan(
		&i.ID,
		&i.WarehouseID,
		&i.Code,
		&i.Zone,
		&i.Rack,
		&i.Level,
		&i.LocType,
		&i.PickSeq,
		&i.Capacity,
		&i.IsActive,
	)
	return i, err
}

const getPartnerByID = `-- name: GetPartnerByID :one
SELECT id, code, partner_type, name, address, contact_name, contact_phone, is_active
FROM master.partners
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPartnerByID(ctx context.Context, id int64) (MasterPartners, error) {
	row := q.db.QueryRow(ctx, getPartnerByID, id)
	var i MasterPartners
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.PartnerType,
		&i.Name,
		&i.Address,
		&i.ContactName,
		&i.ContactPhone,
		&i.IsActive,
	)
	return i, err
}

const getStagingLocation = `-- name: GetStagingLocation :one
SELECT id, warehouse_id, code, zone, rack, level, loc_type, pick_seq, capacity, is_active
FROM master.locations
WHERE warehouse_id = $1 AND loc_type = 'staging' AND is_active = TRUE
ORDER BY code
LIMIT 1
`

func (q *Queries) GetStagingLocation(ctx context.Context, warehouseID int64) (MasterLocations, error) {
	row := q.db.QueryRow(ctx, getStagingLocation, warehouseID)
	var i MasterLocations
	err := row.Scan(
		&i.ID,
		&i.WarehouseID,
		&i.Code,
		&i.Zone,
		&i.Rack,
		&i.Level,
		&i.LocType,
		&i.PickSeq,
		&i.Capacity,
		&i.IsActive,
	)
	return i, err
}

const getStockBalanceByIDForUpdate = `-- name: GetStockBalanceByIDForUpdate :one
SELECT id, item_id, location_id, batch_id, status, qty_onhand, qty_reserved
FROM inv.stock_balances
WHERE id = $1
FOR UPDATE
`

type GetStockBalanceByIDForUpdateRow struct {
	ID          int64          `json:"id"`
	ItemID      int64          `json:"item_id"`
	LocationID  int64          `json:"location_id"`
	BatchID     pgtype.Int8    `json:"batch_id"`
	Status      interface{}    `json:"status"`
	QtyOnhand   pgtype.Numeric `json:"qty_onhand"`
	QtyReserved pgtype.Numeric `json:"qty_reserved"`
}

func (q *Queries) GetStockBalanceByIDForUpdate(ctx context.Context, id int64) (GetStockBalanceByIDForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getStockBalanceByIDForUpdate, id)
	var i GetStockBalanceByIDForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.LocationID,
		&i.BatchID,
		&i.Status,
		&i.QtyOnhand,
		&i.QtyReserved,
	)
	return i, err
}

const getStockBalanceForUpdate = `-- name: GetStockBalanceForUpdate :one
SELECT id, item_id, location_id, batch_id, status, qty_onhand, qty_reserved, updated_at
FROM inv.stock_balances
WHERE item_id = $1 AND location_id = $2 AND COALESCE(batch_id, 0) = COALESCE($3, 0) AND status = $4
FOR UPDATE
`

type GetStockBalanceForUpdateParams struct {
	ItemID     int64       `json:"item_id"`
	LocationID int64       `json:"location_id"`
	BatchID    pgtype.Int8 `json:"batch_id"`
	Status     interface{} `json:"status"`
}

func (q *Queries) GetStockBalanceForUpdate(ctx context.Context, arg GetStockBalanceForUpdateParams) (InvStockBalances, error) {
	row := q.db.QueryRow(ctx, getStockBalanceForUpdate,
		arg.ItemID,
		arg.LocationID,
		arg.BatchID,
		arg.Status,
	)
	var i InvStockBalances
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.LocationID,
		&i.BatchID,
		&i.Status,
		&i.QtyOnhand,
		&i.QtyReserved,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransitLocation = `-- name: GetTransitLocation :one

SELECT id, warehouse_id, code, zone, rack, level, loc_type, pick_seq, capacity, is_active
FROM master.locations
WHERE warehouse_id = $1 AND loc_type = 'transit' AND is_active = TRUE
ORDER BY code
LIMIT 1
`

// ============ FASE 8 (M5 Transfer & M6 Stock Opname) ============
// Lokasi transit gudang tujuan (tempat saldo in_transit dicatat saat /send).
func (q *Queries) GetTransitLocation(ctx context.Context, warehouseID int64) (MasterLocations, error) {
	row := q.db.QueryRow(ctx, getTransitLocation, warehouseID)
	var i MasterLocations
	err := row.Scan(
		&i.ID,
		&i.WarehouseID,
		&i.Code,
		&i.Zone,
		&i.Rack,
		&i.Level,
		&i.LocType,
		&i.PickSeq,
		&i.Capacity,
		&i.IsActive,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, full_name, password_hash, is_active, mfa_secret, last_login_at
FROM sec.users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (SecUsers, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i SecUsers
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.IsActive,
		&i.MfaSecret,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, full_name, password_hash, is_active, mfa_secret, last_login_at
FROM sec.users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (SecUsers, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i SecUsers
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.IsActive,
		&i.MfaSecret,
		&i.LastLoginAt,
	)
	return i, err
}

const getWarehouseByCode = `-- name: GetWarehouseByCode :one
SELECT id, code, name, address, is_active FROM master.warehouses
WHERE code = $1 LIMIT 1
`

func (q *Queries) GetWarehouseByCode(ctx context.Context, code string) (MasterWarehouses, error) {
	row := q.db.QueryRow(ctx, getWarehouseByCode, code)
	var i MasterWarehouses
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Address,
		&i.IsActive,
	)
	return i, err
}

const getWarehouseByID = `-- name: GetWarehouseByID :one

SELECT id, code, name, is_active
FROM master.warehouses
WHERE id = $1
`

type GetWarehouseByIDRow struct {
	ID       int64  `json:"id"`
	Code     string `json:"code"`
	Name     string `json:"name"`
	IsActive bool   `json:"is_active"`
}

// ============ INBOUND (Fase 6 - GRN) ============
func (q *Queries) GetWarehouseByID(ctx context.Context, id int64) (GetWarehouseByIDRow, error) {
	row := q.db.QueryRow(ctx, getWarehouseByID, id)
	var i GetWarehouseByIDRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.IsActive,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO aud.audit_logs (user_id, action, entity, entity_id, old_value, new_value)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAuditLogParams struct {
	UserID   pgtype.Int8 `json:"user_id"`
	Action   string      `json:"action"`
	Entity   string      `json:"entity"`
	EntityID pgtype.Int8 `json:"entity_id"`
	OldValue []byte      `json:"old_value"`
	NewValue []byte      `json:"new_value"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.UserID,
		arg.Action,
		arg.Entity,
		arg.EntityID,
		arg.OldValue,
		arg.NewValue,
	)
	return err
}

const insertStockMovement = `-- name: InsertStockMovement :exec
INSERT INTO inv.stock_movements (item_id, location_id, batch_id, status, movement_type, qty, qty_after, doc_line_id, doc_no, created_by, moved_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW())
`

type InsertStockMovementParams struct {
	ItemID       int64          `json:"item_id"`
	LocationID   int64          `json:"location_id"`
	BatchID      pgtype.Int8    `json:"batch_id"`
	Status       interface{}    `json:"status"`
	MovementType interface{}    `json:"movement_type"`
	Qty          pgtype.Numeric `json:"qty"`
	QtyAfter     pgtype.Numeric `json:"qty_after"`
	DocLineID    pgtype.Int8    `json:"doc_line_id"`
	DocNo        string         `json:"doc_no"`
	CreatedBy    int64          `json:"created_by"`
}

func (q *Queries) InsertStockMovement(ctx context.Context, arg InsertStockMovementParams) error {
	_, err := q.db.Exec(ctx, insertStockMovement,
		arg.ItemID,
		arg.LocationID,
		arg.BatchID,
		arg.Status,
		arg.MovementType,
		arg.Qty,
		arg.QtyAfter,
		arg.DocLineID,
		arg.DocNo,
		arg.CreatedBy,
	)
	return err
}

const listAllocationCandidates = `-- name: ListAllocationCandidates :many

SELECT b.id AS balance_id, b.item_id, b.location_id, b.batch_id,
       b.qty_onhand, b.qty_reserved,
       l.code AS location_code, l.pick_seq, bt.expiry_date
FROM inv.stock_balances b
JOIN master.locations l ON l.id = b.location_id
LEFT JOIN master.batches bt ON bt.id = b.batch_id
WHERE b.item_id = $1
  AND l.warehouse_id = $2
  AND b.status = 'available'
  AND l.loc_type IN ('pick','bulk')
  AND b.qty_onhand > b.qty_reserved
  AND (bt.expiry_date IS NULL OR bt.expiry_date > CURRENT_DATE)
ORDER BY bt.expiry_date NULLS LAST, b.id, l.pick_seq
FOR UPDATE OF b
`

type ListAllocationCandidatesParams struct {
	ItemID      int64 `json:"item_id"`
	WarehouseID int64 `json:"warehouse_id"`
}

type ListAllocationCandidatesRow struct {
	BalanceID    int64          `json:"balance_id"`
	ItemID       int64          `json:"item_id"`
	LocationID   int64          `json:"location_id"`
	BatchID      pgtype.Int8    `json:"batch_id"`
	QtyOnhand    pgtype.Numeric `json:"qty_onhand"`
	QtyReserved  pgtype.Numeric `json:"qty_reserved"`
	LocationCode string         `json:"location_code"`
	PickSeq      pgtype.Int4    `json:"pick_seq"`
	ExpiryDate   pgtype.Date    `json:"expiry_date"`
}

// ============ OUTBOUND (Fase 7 - DO / REQ / FEFO-FIFO) ============
// FEFO/FIFO candidate balances for one item in a warehouse (FSD §4.2).
// Rows are locked (FOR UPDATE OF b — only the balances table, since
// PostgreSQL forbids locking the nullable side of an outer join) so allocation
// is race-safe against concurrent allocators/posters.
func (q *Queries) ListAllocationCandidates(ctx context.Context, arg ListAllocationCandidatesParams) ([]ListAllocationCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listAllocationCandidates, arg.ItemID, arg.WarehouseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllocationCandidatesRow
	for rows.Next() {
		var i ListAllocationCandidatesRow
		if err := rows.Scan(
			&i.BalanceID,
			&i.ItemID,
			&i.LocationID,
			&i.BatchID,
			&i.QtyOnhand,
			&i.QtyReserved,
			&i.LocationCode,
			&i.PickSeq,
			&i.ExpiryDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllocationsByDocument = `-- name: ListAllocationsByDocument :many
SELECT a.id, a.doc_line_id, a.balance_id, a.qty_allocated, a.qty_picked,
       b.item_id, b.location_id, b.batch_id,
       l.code AS location_code, l.pick_seq,
       bt.batch_no, bt.expiry_date,
       i.sku, i.base_uom
FROM doc.allocations a
JOIN inv.stock_balances b ON b.id = a.balance_id
JOIN master.locations l ON l.id = b.location_id
JOIN master.items i ON i.id = b.item_id
LEFT JOIN master.batches bt ON bt.id = b.batch_id
JOIN doc.document_lines dl ON dl.id = a.doc_line_id
WHERE dl.document_id = $1
ORDER BY l.pick_seq NULLS LAST, l.code, a.id
`

type ListAllocationsByDocumentRow struct {
	ID           int64          `json:"id"`
	DocLineID    int64          `json:"doc_line_id"`
	BalanceID    int64          `json:"balance_id"`
	QtyAllocated pgtype.Numeric `json:"qty_allocated"`
	QtyPicked    pgtype.Numeric `json:"qty_picked"`
	ItemID       int64          `json:"item_id"`
	LocationID   int64          `json:"location_id"`
	BatchID      pgtype.Int8    `json:"batch_id"`
	LocationCode string         `json:"location_code"`
	PickSeq      pgtype.Int4    `json:"pick_seq"`
	BatchNo      pgtype.Text    `json:"batch_no"`
	ExpiryDate   pgtype.Date    `json:"expiry_date"`
	Sku          string         `json:"sku"`
	BaseUom      string         `json:"base_uom"`
}

func (q *Queries) ListAllocationsByDocument(ctx context.Context, documentID int64) ([]ListAllocationsByDocumentRow, error) {
	rows, err := q.db.Query(ctx, listAllocationsByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllocationsByDocumentRow
	for rows.Next() {
		var i ListAllocationsByDocumentRow
		if err := rows.Scan(
			&i.ID,
			&i.DocLineID,
			&i.BalanceID,
			&i.QtyAllocated,
			&i.QtyPicked,
			&i.ItemID,
			&i.LocationID,
			&i.BatchID,
			&i.LocationCode,
			&i.PickSeq,
			&i.BatchNo,
			&i.ExpiryDate,
			&i.Sku,
			&i.BaseUom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCountLines = `-- name: ListCountLines :many
SELECT id, document_id, item_id, location_id, batch_id, qty_system, qty_counted, variance, reason_code, counted_by, counted_at
FROM doc.count_lines
WHERE document_id = $1
ORDER BY id
`

func (q *Queries) ListCountLines(ctx context.Context, documentID int64) ([]DocCountLines, error) {
	rows, err := q.db.Query(ctx, listCountLines, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocCountLines
	for rows.Next() {
		var i DocCountLines
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.ItemID,
			&i.LocationID,
			&i.BatchID,
			&i.QtySystem,
			&i.QtyCounted,
			&i.Variance,
			&i.ReasonCode,
			&i.CountedBy,
			&i.CountedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCountSnapshotBalances = `-- name: ListCountSnapshotBalances :many
SELECT b.item_id, b.location_id, b.batch_id, b.status, b.qty_onhand
FROM inv.stock_balances b
JOIN master.locations l ON l.id = b.location_id
WHERE l.warehouse_id = $1
  AND ($2::varchar = '' OR l.zone = $2)
  AND ($3::bigint = 0 OR b.item_id = $3)
  AND b.qty_onhand > 0
ORDER BY b.item_id, b.location_id, COALESCE(b.batch_id, 0)
`

type ListCountSnapshotBalancesParams struct {
	WarehouseID int64  `json:"warehouse_id"`
	Column2     string `json:"column_2"`
	Column3     int64  `json:"column_3"`
}

type ListCountSnapshotBalancesRow struct {
	ItemID     int64          `json:"item_id"`
	LocationID int64          `json:"location_id"`
	BatchID    pgtype.Int8    `json:"batch_id"`
	Status     interface{}    `json:"status"`
	QtyOnhand  pgtype.Numeric `json:"qty_onhand"`
}

// Sumber snapshot qty_system saat sesi opname dibuka (FR-6.1). Scope dapat
// dipersempit per zona (” = semua) dan/atau per item (0 = semua).
func (q *Queries) ListCountSnapshotBalances(ctx context.Context, arg ListCountSnapshotBalancesParams) ([]ListCountSnapshotBalancesRow, error) {
	rows, err := q.db.Query(ctx, listCountSnapshotBalances, arg.WarehouseID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCountSnapshotBalancesRow
	for rows.Next() {
		var i ListCountSnapshotBalancesRow
		if err := rows.Scan(
			&i.ItemID,
			&i.LocationID,
			&i.BatchID,
			&i.Status,
			&i.QtyOnhand,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentLines = `-- name: ListDocumentLines :many
SELECT id, document_id, line_no, item_id, uom, conv_factor, qty_request, qty_processed, batch_id, location_id, status, notes
FROM doc.document_lines
WHERE document_id = $1
ORDER BY line_no
`

func (q *Queries) ListDocumentLines(ctx context.Context, documentID int64) ([]DocDocumentLines, error) {
	rows, err := q.db.Query(ctx, listDocumentLines, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocDocumentLines
	for rows.Next() {
		var i DocDocumentLines
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.LineNo,
			&i.ItemID,
			&i.Uom,
			&i.ConvFactor,
			&i.QtyRequest,
			&i.QtyProcessed,
			&i.BatchID,
			&i.LocationID,
			&i.Status,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemUoMs = `-- name: ListItemUoMs :many
SELECT id, item_id, uom, conv_factor, barcode
FROM master.item_uoms
WHERE item_id = $1
ORDER BY conv_factor
`

func (q *Queries) ListItemUoMs(ctx context.Context, itemID int64) ([]MasterItemUoms, error) {
	rows, err := q.db.Query(ctx, listItemUoMs, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MasterItemUoms
	for rows.Next() {
		var i MasterItemUoms
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.Uom,
			&i.ConvFactor,
			&i.Barcode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItems = `-- name: ListItems :many
SELECT id, public_id, sku, name, category_id, base_uom, is_batch, is_expiry, is_serial, min_qty, max_qty, safety_stock, lead_time_days, abc_class, is_active
FROM master.items
ORDER BY sku
`

type ListItemsRow struct {
	ID           int64          `json:"id"`
	PublicID     pgtype.UUID    `json:"public_id"`
	Sku          string         `json:"sku"`
	Name         string         `json:"name"`
	CategoryID   pgtype.Int8    `json:"category_id"`
	BaseUom      string         `json:"base_uom"`
	IsBatch      bool           `json:"is_batch"`
	IsExpiry     bool           `json:"is_expiry"`
	IsSerial     bool           `json:"is_serial"`
	MinQty       pgtype.Numeric `json:"min_qty"`
	MaxQty       pgtype.Numeric `json:"max_qty"`
	SafetyStock  pgtype.Numeric `json:"safety_stock"`
	LeadTimeDays int16          `json:"lead_time_days"`
	AbcClass     pgtype.Text    `json:"abc_class"`
	IsActive     bool           `json:"is_active"`
}

func (q *Queries) ListItems(ctx context.Context) ([]ListItemsRow, error) {
	rows, err := q.db.Query(ctx, listItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemsRow
	for rows.Next() {
		var i ListItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Sku,
			&i.Name,
			&i.CategoryID,
			&i.BaseUom,
			&i.IsBatch,
			&i.IsExpiry,
			&i.IsSerial,
			&i.MinQty,
			&i.MaxQty,
			&i.SafetyStock,
			&i.LeadTimeDays,
			&i.AbcClass,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocations = `-- name: ListLocations :many
SELECT id, warehouse_id, code, zone, rack, level, loc_type, pick_seq, capacity, is_active
FROM master.locations
WHERE warehouse_id = $1
ORDER BY code
`

func (q *Queries) ListLocations(ctx context.Context, warehouseID int64) ([]MasterLocations, error) {
	rows, err := q.db.Query(ctx, listLocations, warehouseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MasterLocations
	for rows.Next() {
		var i MasterLocations
		if err := rows.Scan(
			&i.ID,
			&i.WarehouseID,
			&i.Code,
			&i.Zone,
			&i.Rack,
			&i.Level,
			&i.LocType,
			&i.PickSeq,
			&i.Capacity,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartners = `-- name: ListPartners :many
SELECT id, code, partner_type, name, address, contact_name, contact_phone, is_active
FROM master.partners
ORDER BY code
`

func (q *Queries) ListPartners(ctx context.Context) ([]MasterPartners, error) {
	rows, err := q.db.Query(ctx, listPartners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MasterPartners
	for rows.Next() {
		var i MasterPartners
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.PartnerType,
			&i.Name,
			&i.Address,
			&i.ContactName,
			&i.ContactPhone,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPutawayCandidates = `-- name: ListPutawayCandidates :many
SELECT l.id, l.warehouse_id, l.code, l.zone, l.rack, l.level, l.loc_type, l.pick_seq, l.capacity,
       COALESCE(SUM(b.qty_onhand), 0)::numeric(18,4) AS used_qty
FROM master.locations l
LEFT JOIN inv.stock_balances b ON b.location_id = l.id AND b.status = 'available'
WHERE l.warehouse_id = $1 AND l.is_active = TRUE AND l.loc_type IN ('pick','bulk')
GROUP BY l.id
ORDER BY l.pick_seq NULLS LAST, l.code
`

type ListPutawayCandidatesRow struct {
	ID          int64          `json:"id"`
	WarehouseID int64          `json:"warehouse_id"`
	Code        string         `json:"code"`
	Zone        pgtype.Text    `json:"zone"`
	Rack        pgtype.Text    `json:"rack"`
	Level       pgtype.Text    `json:"level"`
	LocType     interface{}    `json:"loc_type"`
	PickSeq     pgtype.Int4    `json:"pick_seq"`
	Capacity    pgtype.Numeric `json:"capacity"`
	UsedQty     pgtype.Numeric `json:"used_qty"`
}

func (q *Queries) ListPutawayCandidates(ctx context.Context, warehouseID int64) ([]ListPutawayCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listPutawayCandidates, warehouseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPutawayCandidatesRow
	for rows.Next() {
		var i ListPutawayCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.WarehouseID,
			&i.Code,
			&i.Zone,
			&i.Rack,
			&i.Level,
			&i.LocType,
			&i.PickSeq,
			&i.Capacity,
			&i.UsedQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolePermissions = `-- name: ListRolePermissions :many

SELECT r.code AS role_code, p.code AS permission_code
FROM sec.roles r
JOIN sec.role_permissions rp ON rp.role_id = r.id
JOIN sec.permissions p ON p.id = rp.permission_id
ORDER BY r.code, p.code
`

type ListRolePermissionsRow struct {
	RoleCode       pgtype.Text `json:"role_code"`
	PermissionCode pgtype.Text `json:"permission_code"`
}

// ============ RBAC (Fase 2.4) ============
func (q *Queries) ListRolePermissions(ctx context.Context) ([]ListRolePermissionsRow, error) {
	rows, err := q.db.Query(ctx, listRolePermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRolePermissionsRow
	for rows.Next() {
		var i ListRolePermissionsRow
		if err := rows.Scan(&i.RoleCode, &i.PermissionCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockMovementsKeyset = `-- name: ListStockMovementsKeyset :many
SELECT id, moved_at, item_id, location_id, batch_id, status, movement_type, qty, qty_after, doc_line_id, doc_no, created_by
FROM inv.stock_movements
WHERE moved_at >= $1 AND moved_at <= $2
  AND ($3::bigint = 0 OR item_id = $3)
  AND ($4::bigint = 0 OR location_id = $4)
  AND ($5::boolean = FALSE OR (moved_at < $6::timestamptz OR (moved_at = $6::timestamptz AND id < $7::bigint)))
ORDER BY moved_at DESC, id DESC
LIMIT $8
`

type ListStockMovementsKeysetParams struct {
	MovedAt   pgtype.Timestamptz `json:"moved_at"`
	MovedAt_2 pgtype.Timestamptz `json:"moved_at_2"`
	Column3   int64              `json:"column_3"`
	Column4   int64              `json:"column_4"`
	Column5   bool               `json:"column_5"`
	Column6   pgtype.Timestamptz `json:"column_6"`
	Column7   int64              `json:"column_7"`
	Limit     int32              `json:"limit"`
}

type ListStockMovementsKeysetRow struct {
	ID           int64              `json:"id"`
	MovedAt      pgtype.Timestamptz `json:"moved_at"`
	ItemID       int64              `json:"item_id"`
	LocationID   int64              `json:"location_id"`
	BatchID      pgtype.Int8        `json:"batch_id"`
	Status       interface{}        `json:"status"`
	MovementType interface{}        `json:"movement_type"`
	Qty          pgtype.Numeric     `json:"qty"`
	QtyAfter     pgtype.Numeric     `json:"qty_after"`
	DocLineID    pgtype.Int8        `json:"doc_line_id"`
	DocNo        string             `json:"doc_no"`
	CreatedBy    int64              `json:"created_by"`
}

func (q *Queries) ListStockMovementsKeyset(ctx context.Context, arg ListStockMovementsKeysetParams) ([]ListStockMovementsKeysetRow, error) {
	rows, err := q.db.Query(ctx, listStockMovementsKeyset,
		arg.MovedAt,
		arg.MovedAt_2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStockMovementsKeysetRow
	for rows.Next() {
		var i ListStockMovementsKeysetRow
		if err := rows.Scan(
			&i.ID,
			&i.MovedAt,
			&i.ItemID,
			&i.LocationID,
			&i.BatchID,
			&i.Status,
			&i.MovementType,
			&i.Qty,
			&i.QtyAfter,
			&i.DocLineID,
			&i.DocNo,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransferReceipts = `-- name: ListTransferReceipts :many
SELECT id, document_id, line_id, qty_sent, qty_received, variance, received_by, received_at, notes
FROM doc.transfer_receipts
WHERE document_id = $1
ORDER BY line_id
`

func (q *Queries) ListTransferReceipts(ctx context.Context, documentID int64) ([]DocTransferReceipts, error) {
	rows, err := q.db.Query(ctx, listTransferReceipts, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocTransferReceipts
	for rows.Next() {
		var i DocTransferReceipts
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.LineID,
			&i.QtySent,
			&i.QtyReceived,
			&i.Variance,
			&i.ReceivedBy,
			&i.ReceivedAt,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoleCodes = `-- name: ListUserRoleCodes :many
SELECT DISTINCT COALESCE(r.code, '') AS code
FROM sec.roles r
JOIN sec.user_roles ur ON ur.role_id = r.id
WHERE ur.user_id = $1
ORDER BY code
`

func (q *Queries) ListUserRoleCodes(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserRoleCodes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserWarehouseCodes = `-- name: ListUserWarehouseCodes :many
SELECT DISTINCT w.code
FROM master.warehouses w
JOIN sec.user_roles ur ON ur.warehouse_id = w.id
WHERE ur.user_id = $1
ORDER BY w.code
`

func (q *Queries) ListUserWarehouseCodes(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserWarehouseCodes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWarehouseCodes = `-- name: ListWarehouseCodes :many
SELECT code FROM master.warehouses WHERE is_active = TRUE ORDER BY code
`

func (q *Queries) ListWarehouseCodes(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listWarehouseCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWarehouses = `-- name: ListWarehouses :many
SELECT id, code, name, address, is_active FROM master.warehouses
ORDER BY code
`

func (q *Queries) ListWarehouses(ctx context.Context) ([]MasterWarehouses, error) {
	rows, err := q.db.Query(ctx, listWarehouses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MasterWarehouses
	for rows.Next() {
		var i MasterWarehouses
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Address,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteItem = `-- name: SoftDeleteItem :one
UPDATE master.items
SET is_active = FALSE, updated_at = NOW(), updated_by = $2
WHERE id = $1
RETURNING id, is_active
`

type SoftDeleteItemParams struct {
	ID        int64       `json:"id"`
	UpdatedBy pgtype.Int8 `json:"updated_by"`
}

type SoftDeleteItemRow struct {
	ID       int64 `json:"id"`
	IsActive bool  `json:"is_active"`
}

func (q *Queries) SoftDeleteItem(ctx context.Context, arg SoftDeleteItemParams) (SoftDeleteItemRow, error) {
	row := q.db.QueryRow(ctx, softDeleteItem, arg.ID, arg.UpdatedBy)
	var i SoftDeleteItemRow
	err := row.Scan(&i.ID, &i.IsActive)
	return i, err
}

const updateAllocationPicked = `-- name: UpdateAllocationPicked :exec
UPDATE doc.allocations
SET qty_picked = qty_picked + $2
WHERE id = $1
`

type UpdateAllocationPickedParams struct {
	ID        int64          `json:"id"`
	QtyPicked pgtype.Numeric `json:"qty_picked"`
}

func (q *Queries) UpdateAllocationPicked(ctx context.Context, arg UpdateAllocationPickedParams) error {
	_, err := q.db.Exec(ctx, updateAllocationPicked, arg.ID, arg.QtyPicked)
	return err
}

const updateBalanceReserved = `-- name: UpdateBalanceReserved :exec
UPDATE inv.stock_balances
SET qty_reserved = qty_reserved + $2, updated_at = NOW()
WHERE id = $1
`

type UpdateBalanceReservedParams struct {
	ID          int64          `json:"id"`
	QtyReserved pgtype.Numeric `json:"qty_reserved"`
}

func (q *Queries) UpdateBalanceReserved(ctx context.Context, arg UpdateBalanceReservedParams) error {
	_, err := q.db.Exec(ctx, updateBalanceReserved, arg.ID, arg.QtyReserved)
	return err
}

const updateCountLineCounted = `-- name: UpdateCountLineCounted :exec
UPDATE doc.count_lines
SET qty_counted = $2, reason_code = $3, counted_by = $4, counted_at = NOW()
WHERE id = $1
`

type UpdateCountLineCountedParams struct {
	ID         int64          `json:"id"`
	QtyCounted pgtype.Numeric `json:"qty_counted"`
	ReasonCode pgtype.Text    `json:"reason_code"`
	CountedBy  pgtype.Int8    `json:"counted_by"`
}

func (q *Queries) UpdateCountLineCounted(ctx context.Context, arg UpdateCountLineCountedParams) error {
	_, err := q.db.Exec(ctx, updateCountLineCounted,
		arg.ID,
		arg.QtyCounted,
		arg.ReasonCode,
		arg.CountedBy,
	)
	return err
}

const updateDocumentLineProcessed = `-- name: UpdateDocumentLineProcessed :exec
UPDATE doc.document_lines
SET qty_processed = $2
WHERE id = $1
`

type UpdateDocumentLineProcessedParams struct {
	ID           int64          `json:"id"`
	QtyProcessed pgtype.Numeric `json:"qty_processed"`
}

func (q *Queries) UpdateDocumentLineProcessed(ctx context.Context, arg UpdateDocumentLineProcessedParams) error {
	_, err := q.db.Exec(ctx, updateDocumentLineProcessed, arg.ID, arg.QtyProcessed)
	return err
}

const updateDocumentLinePutaway = `-- name: UpdateDocumentLinePutaway :exec
UPDATE doc.document_lines
SET qty_processed = $2, location_id = $3
WHERE id = $1
`

type UpdateDocumentLinePutawayParams struct {
	ID           int64          `json:"id"`
	QtyProcessed pgtype.Numeric `json:"qty_processed"`
	LocationID   pgtype.Int8    `json:"location_id"`
}

func (q *Queries) UpdateDocumentLinePutaway(ctx context.Context, arg UpdateDocumentLinePutawayParams) error {
	_, err := q.db.Exec(ctx, updateDocumentLinePutaway, arg.ID, arg.QtyProcessed, arg.LocationID)
	return err
}

const updateDocumentManagerApproval = `-- name: UpdateDocumentManagerApproval :exec
UPDATE doc.documents
SET manager_approved_by = $2, manager_approved_at = NOW()
WHERE id = $1
`

type UpdateDocumentManagerApprovalParams struct {
	ID                int64       `json:"id"`
	ManagerApprovedBy pgtype.Int8 `json:"manager_approved_by"`
}

func (q *Queries) UpdateDocumentManagerApproval(ctx context.Context, arg UpdateDocumentManagerApprovalParams) error {
	_, err := q.db.Exec(ctx, updateDocumentManagerApproval, arg.ID, arg.ManagerApprovedBy)
	return err
}

const updateDocumentReasonCode = `-- name: UpdateDocumentReasonCode :exec
UPDATE doc.documents
SET reason_code = $2
WHERE id = $1
`

type UpdateDocumentReasonCodeParams struct {
	ID         int64       `json:"id"`
	ReasonCode pgtype.Text `json:"reason_code"`
}

func (q *Queries) UpdateDocumentReasonCode(ctx context.Context, arg UpdateDocumentReasonCodeParams) error {
	_, err := q.db.Exec(ctx, updateDocumentReasonCode, arg.ID, arg.ReasonCode)
	return err
}

const updateDocumentStatus = `-- name: UpdateDocumentStatus :exec
UPDATE doc.documents
SET status = $2::doc.doc_status,
    submitted_at = CASE WHEN $2::doc.doc_status = 'submitted' THEN NOW() ELSE submitted_at END,
    approved_at  = CASE WHEN $2::doc.doc_status = 'approved' THEN NOW() ELSE approved_at END,
    approved_by  = CASE WHEN $2::doc.doc_status = 'approved' THEN $3 ELSE approved_by END,
    completed_at = CASE WHEN $2::doc.doc_status = 'completed' THEN NOW() ELSE completed_at END
WHERE id = $1
`

type UpdateDocumentStatusParams struct {
	ID         int64       `json:"id"`
	Column2    interface{} `json:"column_2"`
	ApprovedBy pgtype.Int8 `json:"approved_by"`
}

func (q *Queries) UpdateDocumentStatus(ctx context.Context, arg UpdateDocumentStatusParams) error {
	_, err := q.db.Exec(ctx, updateDocumentStatus, arg.ID, arg.Column2, arg.ApprovedBy)
	return err
}

const updateItem = `-- name: UpdateItem :one
UPDATE master.items
SET name = $2, category_id = $3, base_uom = $4, is_batch = $5, is_expiry = $6, is_serial = $7,
    min_qty = $8, max_qty = $9, safety_stock = $10, lead_time_days = $11, abc_class = $12, is_active = $13,
    updated_at = NOW(), updated_by = $14
WHERE id = $1
RETURNING id, public_id, sku, name, category_id, base_uom, is_batch, is_expiry, is_serial, min_qty, max_qty, safety_stock, lead_time_days, abc_class, is_active, updated_at, updated_by
`

type UpdateItemParams struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	CategoryID   pgtype.Int8    `json:"category_id"`
	BaseUom      string         `json:"base_uom"`
	IsBatch      bool           `json:"is_batch"`
	IsExpiry     bool           `json:"is_expiry"`
	IsSerial     bool           `json:"is_serial"`
	MinQty       pgtype.Numeric `json:"min_qty"`
	MaxQty       pgtype.Numeric `json:"max_qty"`
	SafetyStock  pgtype.Numeric `json:"safety_stock"`
	LeadTimeDays int16          `json:"lead_time_days"`
	AbcClass     pgtype.Text    `json:"abc_class"`
	IsActive     bool           `json:"is_active"`
	UpdatedBy    pgtype.Int8    `json:"updated_by"`
}

type UpdateItemRow struct {
	ID           int64              `json:"id"`
	PublicID     pgtype.UUID        `json:"public_id"`
	Sku          string             `json:"sku"`
	Name         string             `json:"name"`
	CategoryID   pgtype.Int8        `json:"category_id"`
	BaseUom      string             `json:"base_uom"`
	IsBatch      bool               `json:"is_batch"`
	IsExpiry     bool               `json:"is_expiry"`
	IsSerial     bool               `json:"is_serial"`
	MinQty       pgtype.Numeric     `json:"min_qty"`
	MaxQty       pgtype.Numeric     `json:"max_qty"`
	SafetyStock  pgtype.Numeric     `json:"safety_stock"`
	LeadTimeDays int16              `json:"lead_time_days"`
	AbcClass     pgtype.Text        `json:"abc_class"`
	IsActive     bool               `json:"is_active"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy    pgtype.Int8        `json:"updated_by"`
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (UpdateItemRow, error) {
	row := q.db.QueryRow(ctx, updateItem,
		arg.ID,
		arg.Name,
		arg.CategoryID,
		arg.BaseUom,
		arg.IsBatch,
		arg.IsExpiry,
		arg.IsSerial,
		arg.MinQty,
		arg.MaxQty,
		arg.SafetyStock,
		arg.LeadTimeDays,
		arg.AbcClass,
		arg.IsActive,
		arg.UpdatedBy,
	)
	var i UpdateItemRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Sku,
		&i.Name,
		&i.CategoryID,
		&i.BaseUom,
		&i.IsBatch,
		&i.IsExpiry,
		&i.IsSerial,
		&i.MinQty,
		&i.MaxQty,
		&i.SafetyStock,
		&i.LeadTimeDays,
		&i.AbcClass,
		&i.IsActive,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const updateLocation = `-- name: UpdateLocation :one
UPDATE master.locations
SET code = $2, zone = $3, rack = $4, level = $5, loc_type = $6, pick_seq = $7, capacity = $8, is_active = $9
WHERE id = $1
RETURNING id, warehouse_id, code, zone, rack, level, loc_type, pick_seq, capacity, is_active
`

type UpdateLocationParams struct {
	ID       int64          `json:"id"`
	Code     string         `json:"code"`
	Zone     pgtype.Text    `json:"zone"`
	Rack     pgtype.Text    `json:"rack"`
	Level    pgtype.Text    `json:"level"`
	LocType  interface{}    `json:"loc_type"`
	PickSeq  pgtype.Int4    `json:"pick_seq"`
	Capacity pgtype.Numeric `json:"capacity"`
	IsActive bool           `json:"is_active"`
}

func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) (MasterLocations, error) {
	row := q.db.QueryRow(ctx, updateLocation,
		arg.ID,
		arg.Code,
		arg.Zone,
		arg.Rack,
		arg.Level,
		arg.LocType,
		arg.PickSeq,
		arg.Capacity,
		arg.IsActive,
	)
	var i MasterLocations
	err := row.Scan(
		&i.ID,
		&i.WarehouseID,
		&i.Code,
		&i.Zone,
		&i.Rack,
		&i.Level,
		&i.LocType,
		&i.PickSeq,
		&i.Capacity,
		&i.IsActive,
	)
	return i, err
}

const updatePartner = `-- name: UpdatePartner :one
UPDATE master.partners
SET code = $2, partner_type = $3, name = $4, address = $5, contact_name = $6, contact_phone = $7, is_active = $8
WHERE id = $1
RETURNING id, code, partner_type, name, address, contact_name, contact_phone, is_active
`

type UpdatePartnerParams struct {
	ID           int64       `json:"id"`
	Code         string      `json:"code"`
	PartnerType  string      `json:"partner_type"`
	Name         string      `json:"name"`
	Address      pgtype.Text `json:"address"`
	ContactName  pgtype.Text `json:"contact_name"`
	ContactPhone pgtype.Text `json:"contact_phone"`
	IsActive     bool        `json:"is_active"`
}

func (q *Queries) UpdatePartner(ctx context.Context, arg UpdatePartnerParams) (MasterPartners, error) {
	row := q.db.QueryRow(ctx, updatePartner,
		arg.ID,
		arg.Code,
		arg.PartnerType,
		arg.Name,
		arg.Address,
		arg.ContactName,
		arg.ContactPhone,
		arg.IsActive,
	)
	var i MasterPartners
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.PartnerType,
		&i.Name,
		&i.Address,
		&i.ContactName,
		&i.ContactPhone,
		&i.IsActive,
	)
	return i, err
}

const updateStockBalanceQty = `-- name: UpdateStockBalanceQty :one
UPDATE inv.stock_balances
SET qty_onhand = $2, qty_reserved = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, qty_onhand, qty_reserved
`

type UpdateStockBalanceQtyParams struct {
	ID          int64          `json:"id"`
	QtyOnhand   pgtype.Numeric `json:"qty_onhand"`
	QtyReserved pgtype.Numeric `json:"qty_reserved"`
}

type UpdateStockBalanceQtyRow struct {
	ID          int64          `json:"id"`
	QtyOnhand   pgtype.Numeric `json:"qty_onhand"`
	QtyReserved pgtype.Numeric `json:"qty_reserved"`
}

func (q *Queries) UpdateStockBalanceQty(ctx context.Context, arg UpdateStockBalanceQtyParams) (UpdateStockBalanceQtyRow, error) {
	row := q.db.QueryRow(ctx, updateStockBalanceQty, arg.ID, arg.QtyOnhand, arg.QtyReserved)
	var i UpdateStockBalanceQtyRow
	err := row.Scan(&i.ID, &i.QtyOnhand, &i.QtyReserved)
	return i, err
}

const upsertDelivery = `-- name: UpsertDelivery :exec
INSERT INTO doc.deliveries (document_id, vehicle_no, driver_name, shipped_at, received_by, received_at, pod_file_url, signature_url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (document_id) DO UPDATE SET
    vehicle_no    = COALESCE(EXCLUDED.vehicle_no,    doc.deliveries.vehicle_no),
    driver_name   = COALESCE(EXCLUDED.driver_name,   doc.deliveries.driver_name),
    shipped_at    = COALESCE(EXCLUDED.shipped_at,    doc.deliveries.shipped_at),
    received_by   = COALESCE(EXCLUDED.received_by,   doc.deliveries.received_by),
    received_at   = COALESCE(EXCLUDED.received_at,   doc.deliveries.received_at),
    pod_file_url  = COALESCE(EXCLUDED.pod_file_url,  doc.deliveries.pod_file_url),
    signature_url = COALESCE(EXCLUDED.signature_url, doc.deliveries.signature_url)
`

type UpsertDeliveryParams struct {
	DocumentID   int64              `json:"document_id"`
	VehicleNo    pgtype.Text        `json:"vehicle_no"`
	DriverName   pgtype.Text        `json:"driver_name"`
	ShippedAt    pgtype.Timestamptz `json:"shipped_at"`
	ReceivedBy   pgtype.Text        `json:"received_by"`
	ReceivedAt   pgtype.Timestamptz `json:"received_at"`
	PodFileUrl   pgtype.Text        `json:"pod_file_url"`
	SignatureUrl pgtype.Text        `json:"signature_url"`
}

func (q *Queries) UpsertDelivery(ctx context.Context, arg UpsertDeliveryParams) error {
	_, err := q.db.Exec(ctx, upsertDelivery,
		arg.DocumentID,
		arg.VehicleNo,
		arg.DriverName,
		arg.ShippedAt,
		arg.ReceivedBy,
		arg.ReceivedAt,
		arg.PodFileUrl,
		arg.SignatureUrl,
	)
	return err
}

const upsertDocumentNumber = `-- name: UpsertDocumentNumber :one

INSERT INTO doc.document_numbers (doc_type, period, last_seq)
VALUES ($1, $2, 1)
ON CONFLICT (doc_type, period)
DO UPDATE SET last_seq = doc.document_numbers.last_seq + 1
RETURNING last_seq
`

type UpsertDocumentNumberParams struct {
	DocType interface{} `json:"doc_type"`
	Period  string      `json:"period"`
}

// ============ Dokumen (Fase 5.1 - BR-04) ============
// Atomic sequence bump: returns the next sequence for (doc_type, period).
// Must run inside the same transaction that creates the document (FSD 4.3).
// Period is computed by the application from the same clock as the document
// number so the sequence and the formatted number can never diverge.
func (q *Queries) UpsertDocumentNumber(ctx context.Context, arg UpsertDocumentNumberParams) (int32, error) {
	row := q.db.QueryRow(ctx, upsertDocumentNumber, arg.DocType, arg.Period)
	var last_seq int32
	err := row.Scan(&last_seq)
	return last_seq, err
}

const upsertStockBalance = `-- name: UpsertStockBalance :one

INSERT INTO inv.stock_balances (item_id, location_id, batch_id, status, qty_onhand, qty_reserved, updated_at)
VALUES ($1, $2, $3, $4, 0, 0, NOW())
ON CONFLICT (item_id, location_id, COALESCE(batch_id, 0), status) DO UPDATE SET updated_at = NOW()
RETURNING id, qty_onhand, qty_reserved
`

type UpsertStockBalanceParams struct {
	ItemID     int64       `json:"item_id"`
	LocationID int64       `json:"location_id"`
	BatchID    pgtype.Int8 `json:"batch_id"`
	Status     interface{} `json:"status"`
}

type UpsertStockBalanceRow struct {
	ID          int64          `json:"id"`
	QtyOnhand   pgtype.Numeric `json:"qty_onhand"`
	QtyReserved pgtype.Numeric `json:"qty_reserved"`
}

// ============ STOCK BALANCES & MOVEMENTS ============
func (q *Queries) UpsertStockBalance(ctx context.Context, arg UpsertStockBalanceParams) (UpsertStockBalanceRow, error) {
	row := q.db.QueryRow(ctx, upsertStockBalance,
		arg.ItemID,
		arg.LocationID,
		arg.BatchID,
		arg.Status,
	)
	var i UpsertStockBalanceRow
	err := row.Scan(&i.ID, &i.QtyOnhand, &i.QtyReserved)
	return i, err
}

const upsertStockBalanceFull = `-- name: UpsertStockBalanceFull :exec
INSERT INTO inv.stock_balances (item_id, location_id, batch_id, status, qty_onhand, qty_reserved, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
ON CONFLICT (item_id, location_id, COALESCE(batch_id, 0), status)
DO UPDATE SET qty_onhand = EXCLUDED.qty_onhand, qty_reserved = EXCLUDED.qty_reserved, updated_at = NOW()
`

type UpsertStockBalanceFullParams struct {
	ItemID      int64          `json:"item_id"`
	LocationID  int64          `json:"location_id"`
	BatchID     pgtype.Int8    `json:"batch_id"`
	Status      interface{}    `json:"status"`
	QtyOnhand   pgtype.Numeric `json:"qty_onhand"`
	QtyReserved pgtype.Numeric `json:"qty_reserved"`
}

func (q *Queries) UpsertStockBalanceFull(ctx context.Context, arg UpsertStockBalanceFullParams) error {
	_, err := q.db.Exec(ctx, upsertStockBalanceFull,
		arg.ItemID,
		arg.LocationID,
		arg.BatchID,
		arg.Status,
		arg.QtyOnhand,
		arg.QtyReserved,
	)
	return err
}
