// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AudAuditLogs struct {
	ID         int64              `json:"id"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	UserID     pgtype.Int8        `json:"user_id"`
	Action     string             `json:"action"`
	Entity     string             `json:"entity"`
	EntityID   pgtype.Int8        `json:"entity_id"`
	OldValue   []byte             `json:"old_value"`
	NewValue   []byte             `json:"new_value"`
	IpAddress  *netip.Addr        `json:"ip_address"`
	RequestID  pgtype.UUID        `json:"request_id"`
}

type DocAllocations struct {
	ID           int64              `json:"id"`
	DocLineID    int64              `json:"doc_line_id"`
	BalanceID    int64              `json:"balance_id"`
	QtyAllocated pgtype.Numeric     `json:"qty_allocated"`
	QtyPicked    pgtype.Numeric     `json:"qty_picked"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type DocCountLines struct {
	ID         int64              `json:"id"`
	DocumentID int64              `json:"document_id"`
	ItemID     int64              `json:"item_id"`
	LocationID int64              `json:"location_id"`
	BatchID    pgtype.Int8        `json:"batch_id"`
	QtySystem  pgtype.Numeric     `json:"qty_system"`
	QtyCounted pgtype.Numeric     `json:"qty_counted"`
	Variance   pgtype.Numeric     `json:"variance"`
	ReasonCode pgtype.Text        `json:"reason_code"`
	CountedBy  pgtype.Int8        `json:"counted_by"`
	CountedAt  pgtype.Timestamptz `json:"counted_at"`
}

type DocDeliveries struct {
	DocumentID   int64              `json:"document_id"`
	VehicleNo    pgtype.Text        `json:"vehicle_no"`
	DriverName   pgtype.Text        `json:"driver_name"`
	ShippedAt    pgtype.Timestamptz `json:"shipped_at"`
	ReceivedBy   pgtype.Text        `json:"received_by"`
	ReceivedAt   pgtype.Timestamptz `json:"received_at"`
	PodFileUrl   pgtype.Text        `json:"pod_file_url"`
	SignatureUrl pgtype.Text        `json:"signature_url"`
}

type DocDocumentLines struct {
	ID           int64          `json:"id"`
	DocumentID   int64          `json:"document_id"`
	LineNo       int16          `json:"line_no"`
	ItemID       int64          `json:"item_id"`
	Uom          string         `json:"uom"`
	ConvFactor   pgtype.Numeric `json:"conv_factor"`
	QtyRequest   pgtype.Numeric `json:"qty_request"`
	QtyProcessed pgtype.Numeric `json:"qty_processed"`
	BatchID      pgtype.Int8    `json:"batch_id"`
	LocationID   pgtype.Int8    `json:"location_id"`
	Status       interface{}    `json:"status"`
	Notes        pgtype.Text    `json:"notes"`
}

type DocDocumentNumbers struct {
	DocType interface{} `json:"doc_type"`
	Period  string      `json:"period"`
	LastSeq int32       `json:"last_seq"`
}

type DocDocuments struct {
	ID                int64              `json:"id"`
	PublicID          pgtype.UUID        `json:"public_id"`
	DocNo             string             `json:"doc_no"`
	DocType           interface{}        `json:"doc_type"`
	DocDate           pgtype.Date        `json:"doc_date"`
	Status            interface{}        `json:"status"`
	WarehouseID       int64              `json:"warehouse_id"`
	DestWarehouseID   pgtype.Int8        `json:"dest_warehouse_id"`
	PartnerID         pgtype.Int8        `json:"partner_id"`
	RefDocID          pgtype.Int8        `json:"ref_doc_id"`
	ReasonCode        pgtype.Text        `json:"reason_code"`
	Notes             pgtype.Text        `json:"notes"`
	IdempotencyKey    pgtype.Text        `json:"idempotency_key"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	CreatedBy         int64              `json:"created_by"`
	SubmittedAt       pgtype.Timestamptz `json:"submitted_at"`
	ApprovedAt        pgtype.Timestamptz `json:"approved_at"`
	ApprovedBy        pgtype.Int8        `json:"approved_by"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	ManagerApprovedBy pgtype.Int8        `json:"manager_approved_by"`
	ManagerApprovedAt pgtype.Timestamptz `json:"manager_approved_at"`
}

type DocTransferReceipts struct {
	ID          int64              `json:"id"`
	DocumentID  int64              `json:"document_id"`
	LineID      int64              `json:"line_id"`
	QtySent     pgtype.Numeric     `json:"qty_sent"`
	QtyReceived pgtype.Numeric     `json:"qty_received"`
	Variance    pgtype.Numeric     `json:"variance"`
	ReceivedBy  int64              `json:"received_by"`
	ReceivedAt  pgtype.Timestamptz `json:"received_at"`
	Notes       pgtype.Text        `json:"notes"`
}

type InvStockBalances struct {
	ID          int64              `json:"id"`
	ItemID      int64              `json:"item_id"`
	LocationID  int64              `json:"location_id"`
	BatchID     pgtype.Int8        `json:"batch_id"`
	Status      interface{}        `json:"status"`
	QtyOnhand   pgtype.Numeric     `json:"qty_onhand"`
	QtyReserved pgtype.Numeric     `json:"qty_reserved"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type InvStockMovements struct {
	ID           int64              `json:"id"`
	MovedAt      pgtype.Timestamptz `json:"moved_at"`
	ItemID       int64              `json:"item_id"`
	LocationID   int64              `json:"location_id"`
	BatchID      pgtype.Int8        `json:"batch_id"`
	Status       interface{}        `json:"status"`
	MovementType interface{}        `json:"movement_type"`
	Qty          pgtype.Numeric     `json:"qty"`
	QtyAfter     pgtype.Numeric     `json:"qty_after"`
	UnitCost     pgtype.Numeric     `json:"unit_cost"`
	DocLineID    pgtype.Int8        `json:"doc_line_id"`
	DocNo        string             `json:"doc_no"`
	CreatedBy    int64              `json:"created_by"`
}

type InvStockMovementsDefault struct {
	ID           int64              `json:"id"`
	MovedAt      pgtype.Timestamptz `json:"moved_at"`
	ItemID       int64              `json:"item_id"`
	LocationID   int64              `json:"location_id"`
	BatchID      pgtype.Int8        `json:"batch_id"`
	Status       interface{}        `json:"status"`
	MovementType interface{}        `json:"movement_type"`
	Qty          pgtype.Numeric     `json:"qty"`
	QtyAfter     pgtype.Numeric     `json:"qty_after"`
	UnitCost     pgtype.Numeric     `json:"unit_cost"`
	DocLineID    pgtype.Int8        `json:"doc_line_id"`
	DocNo        string             `json:"doc_no"`
	CreatedBy    int64              `json:"created_by"`
}

type MasterBatches struct {
	ID         int64       `json:"id"`
	ItemID     int64       `json:"item_id"`
	BatchNo    string      `json:"batch_no"`
	MfgDate    pgtype.Date `json:"mfg_date"`
	ExpiryDate pgtype.Date `json:"expiry_date"`
}

type MasterCategories struct {
	ID       int64  `json:"id"`
	Code     string `json:"code"`
	Name     string `json:"name"`
	IsActive bool   `json:"is_active"`
}

type MasterItemUoms struct {
	ID         int64          `json:"id"`
	ItemID     int64          `json:"item_id"`
	Uom        string         `json:"uom"`
	ConvFactor pgtype.Numeric `json:"conv_factor"`
	Barcode    pgtype.Text    `json:"barcode"`
}

type MasterItems struct {
	ID           int64              `json:"id"`
	PublicID     pgtype.UUID        `json:"public_id"`
	Sku          string             `json:"sku"`
	Name         string             `json:"name"`
	CategoryID   pgtype.Int8        `json:"category_id"`
	BaseUom      string             `json:"base_uom"`
	IsBatch      bool               `json:"is_batch"`
	IsExpiry     bool               `json:"is_expiry"`
	IsSerial     bool               `json:"is_serial"`
	MinQty       pgtype.Numeric     `json:"min_qty"`
	MaxQty       pgtype.Numeric     `json:"max_qty"`
	SafetyStock  pgtype.Numeric     `json:"safety_stock"`
	LeadTimeDays int16              `json:"lead_time_days"`
	AbcClass     pgtype.Text        `json:"abc_class"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CreatedBy    int64              `json:"created_by"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy    pgtype.Int8        `json:"updated_by"`
}

type MasterLocations struct {
	ID          int64          `json:"id"`
	WarehouseID int64          `json:"warehouse_id"`
	Code        string         `json:"code"`
	Zone        pgtype.Text    `json:"zone"`
	Rack        pgtype.Text    `json:"rack"`
	Level       pgtype.Text    `json:"level"`
	LocType     interface{}    `json:"loc_type"`
	PickSeq     pgtype.Int4    `json:"pick_seq"`
	Capacity    pgtype.Numeric `json:"capacity"`
	IsActive    bool           `json:"is_active"`
}

type MasterPartners struct {
	ID           int64       `json:"id"`
	Code         string      `json:"code"`
	PartnerType  string      `json:"partner_type"`
	Name         string      `json:"name"`
	Address      pgtype.Text `json:"address"`
	ContactName  pgtype.Text `json:"contact_name"`
	ContactPhone pgtype.Text `json:"contact_phone"`
	IsActive     bool        `json:"is_active"`
}

type MasterWarehouses struct {
	ID       int64       `json:"id"`
	Code     string      `json:"code"`
	Name     string      `json:"name"`
	Address  pgtype.Text `json:"address"`
	IsActive bool        `json:"is_active"`
}

type SecPermissions struct {
	ID   int64       `json:"id"`
	Code pgtype.Text `json:"code"`
}

type SecRolePermissions struct {
	RoleID       int64 `json:"role_id"`
	PermissionID int64 `json:"permission_id"`
}

type SecRoles struct {
	ID   int64       `json:"id"`
	Code pgtype.Text `json:"code"`
	Name pgtype.Text `json:"name"`
}

type SecUserRoles struct {
	UserID      int64 `json:"user_id"`
	RoleID      int64 `json:"role_id"`
	WarehouseID int64 `json:"warehouse_id"`
}

type SecUsers struct {
	ID           int64              `json:"id"`
	Username     string             `json:"username"`
	Email        pgtype.Text        `json:"email"`
	FullName     string             `json:"full_name"`
	PasswordHash string             `json:"password_hash"`
	IsActive     bool               `json:"is_active"`
	MfaSecret    pgtype.Text        `json:"mfa_secret"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
}
