-- ============ DROP TABLES ============
DROP TABLE IF EXISTS aud.audit_logs CASCADE;
DROP TABLE IF EXISTS sec.user_roles CASCADE;
DROP TABLE IF EXISTS sec.role_permissions CASCADE;
DROP TABLE IF EXISTS sec.permissions CASCADE;
DROP TABLE IF EXISTS sec.roles CASCADE;
DROP TABLE IF EXISTS sec.users CASCADE;
DROP TABLE IF EXISTS doc.count_lines CASCADE;
DROP TABLE IF EXISTS doc.deliveries CASCADE;
DROP TABLE IF EXISTS doc.document_numbers CASCADE;
DROP TABLE IF EXISTS doc.allocations CASCADE;
DROP TABLE IF EXISTS inv.stock_movements CASCADE;
DROP TABLE IF EXISTS doc.document_lines CASCADE;
DROP TABLE IF EXISTS doc.documents CASCADE;
DROP TABLE IF EXISTS inv.stock_balances CASCADE;
DROP TABLE IF EXISTS master.partners CASCADE;
DROP TABLE IF EXISTS master.batches CASCADE;
DROP TABLE IF EXISTS master.locations CASCADE;
DROP TABLE IF EXISTS master.warehouses CASCADE;
DROP TABLE IF EXISTS master.item_uoms CASCADE;
DROP TABLE IF EXISTS master.items CASCADE;
DROP TABLE IF EXISTS master.categories CASCADE;

-- ============ DROP TYPES ============
DROP TYPE IF EXISTS doc.doc_status CASCADE;
DROP TYPE IF EXISTS doc.doc_type CASCADE;
DROP TYPE IF EXISTS inv.movement_type CASCADE;
DROP TYPE IF EXISTS inv.stock_status CASCADE;
DROP TYPE IF EXISTS inv.location_type CASCADE;

-- ============ DROP SCHEMAS ============
DROP SCHEMA IF EXISTS aud CASCADE;
DROP SCHEMA IF EXISTS sec CASCADE;
DROP SCHEMA IF EXISTS doc CASCADE;
DROP SCHEMA IF EXISTS inv CASCADE;
DROP SCHEMA IF EXISTS master CASCADE;
