// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: init.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one

INSERT INTO master.categories (code, name, is_active)
VALUES ($1, $2, $3)
RETURNING id, code, name, is_active
`

type CreateCategoryParams struct {
	Code     string `json:"code"`
	Name     string `json:"name"`
	IsActive bool   `json:"is_active"`
}

// ============ CATEGORIES ============
func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (MasterCategories, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Code, arg.Name, arg.IsActive)
	var i MasterCategories
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.IsActive,
	)
	return i, err
}

const createItem = `-- name: CreateItem :one

INSERT INTO master.items (
    sku, name, category_id, base_uom, is_batch, is_expiry, is_serial,
    min_qty, max_qty, safety_stock, lead_time_days, abc_class, is_active, created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, public_id, sku, name, category_id, base_uom, is_batch, is_expiry, is_serial, min_qty, max_qty, safety_stock, lead_time_days, abc_class, is_active, created_at, created_by
`

type CreateItemParams struct {
	Sku          string         `json:"sku"`
	Name         string         `json:"name"`
	CategoryID   pgtype.Int8    `json:"category_id"`
	BaseUom      string         `json:"base_uom"`
	IsBatch      bool           `json:"is_batch"`
	IsExpiry     bool           `json:"is_expiry"`
	IsSerial     bool           `json:"is_serial"`
	MinQty       pgtype.Numeric `json:"min_qty"`
	MaxQty       pgtype.Numeric `json:"max_qty"`
	SafetyStock  pgtype.Numeric `json:"safety_stock"`
	LeadTimeDays int16          `json:"lead_time_days"`
	AbcClass     pgtype.Text    `json:"abc_class"`
	IsActive     bool           `json:"is_active"`
	CreatedBy    int64          `json:"created_by"`
}

type CreateItemRow struct {
	ID           int64              `json:"id"`
	PublicID     pgtype.UUID        `json:"public_id"`
	Sku          string             `json:"sku"`
	Name         string             `json:"name"`
	CategoryID   pgtype.Int8        `json:"category_id"`
	BaseUom      string             `json:"base_uom"`
	IsBatch      bool               `json:"is_batch"`
	IsExpiry     bool               `json:"is_expiry"`
	IsSerial     bool               `json:"is_serial"`
	MinQty       pgtype.Numeric     `json:"min_qty"`
	MaxQty       pgtype.Numeric     `json:"max_qty"`
	SafetyStock  pgtype.Numeric     `json:"safety_stock"`
	LeadTimeDays int16              `json:"lead_time_days"`
	AbcClass     pgtype.Text        `json:"abc_class"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CreatedBy    int64              `json:"created_by"`
}

// ============ ITEMS & UOMS ============
func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (CreateItemRow, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.Sku,
		arg.Name,
		arg.CategoryID,
		arg.BaseUom,
		arg.IsBatch,
		arg.IsExpiry,
		arg.IsSerial,
		arg.MinQty,
		arg.MaxQty,
		arg.SafetyStock,
		arg.LeadTimeDays,
		arg.AbcClass,
		arg.IsActive,
		arg.CreatedBy,
	)
	var i CreateItemRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Sku,
		&i.Name,
		&i.CategoryID,
		&i.BaseUom,
		&i.IsBatch,
		&i.IsExpiry,
		&i.IsSerial,
		&i.MinQty,
		&i.MaxQty,
		&i.SafetyStock,
		&i.LeadTimeDays,
		&i.AbcClass,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const createItemUoM = `-- name: CreateItemUoM :one
INSERT INTO master.item_uoms (item_id, uom, conv_factor, barcode)
VALUES ($1, $2, $3, $4)
RETURNING id, item_id, uom, conv_factor, barcode
`

type CreateItemUoMParams struct {
	ItemID     int64          `json:"item_id"`
	Uom        string         `json:"uom"`
	ConvFactor pgtype.Numeric `json:"conv_factor"`
	Barcode    pgtype.Text    `json:"barcode"`
}

func (q *Queries) CreateItemUoM(ctx context.Context, arg CreateItemUoMParams) (MasterItemUoms, error) {
	row := q.db.QueryRow(ctx, createItemUoM,
		arg.ItemID,
		arg.Uom,
		arg.ConvFactor,
		arg.Barcode,
	)
	var i MasterItemUoms
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Uom,
		&i.ConvFactor,
		&i.Barcode,
	)
	return i, err
}

const createLocation = `-- name: CreateLocation :one

INSERT INTO master.locations (warehouse_id, code, zone, rack, level, loc_type, pick_seq, capacity, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, warehouse_id, code, zone, rack, level, loc_type, pick_seq, capacity, is_active
`

type CreateLocationParams struct {
	WarehouseID int64          `json:"warehouse_id"`
	Code        string         `json:"code"`
	Zone        pgtype.Text    `json:"zone"`
	Rack        pgtype.Text    `json:"rack"`
	Level       pgtype.Text    `json:"level"`
	LocType     interface{}    `json:"loc_type"`
	PickSeq     pgtype.Int4    `json:"pick_seq"`
	Capacity    pgtype.Numeric `json:"capacity"`
	IsActive    bool           `json:"is_active"`
}

// ============ LOCATIONS ============
func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (MasterLocations, error) {
	row := q.db.QueryRow(ctx, createLocation,
		arg.WarehouseID,
		arg.Code,
		arg.Zone,
		arg.Rack,
		arg.Level,
		arg.LocType,
		arg.PickSeq,
		arg.Capacity,
		arg.IsActive,
	)
	var i MasterLocations
	err := row.Scan(
		&i.ID,
		&i.WarehouseID,
		&i.Code,
		&i.Zone,
		&i.Rack,
		&i.Level,
		&i.LocType,
		&i.PickSeq,
		&i.Capacity,
		&i.IsActive,
	)
	return i, err
}

const createPartner = `-- name: CreatePartner :one

INSERT INTO master.partners (code, partner_type, name, address, contact_name, contact_phone, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, code, partner_type, name, address, contact_name, contact_phone, is_active
`

type CreatePartnerParams struct {
	Code         string      `json:"code"`
	PartnerType  string      `json:"partner_type"`
	Name         string      `json:"name"`
	Address      pgtype.Text `json:"address"`
	ContactName  pgtype.Text `json:"contact_name"`
	ContactPhone pgtype.Text `json:"contact_phone"`
	IsActive     bool        `json:"is_active"`
}

// ============ PARTNERS ============
func (q *Queries) CreatePartner(ctx context.Context, arg CreatePartnerParams) (MasterPartners, error) {
	row := q.db.QueryRow(ctx, createPartner,
		arg.Code,
		arg.PartnerType,
		arg.Name,
		arg.Address,
		arg.ContactName,
		arg.ContactPhone,
		arg.IsActive,
	)
	var i MasterPartners
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.PartnerType,
		&i.Name,
		&i.Address,
		&i.ContactName,
		&i.ContactPhone,
		&i.IsActive,
	)
	return i, err
}

const createStockMovement = `-- name: CreateStockMovement :one
INSERT INTO inv.stock_movements (item_id, location_id, batch_id, status, movement_type, qty, qty_after, doc_line_id, doc_no, created_by, moved_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW())
RETURNING id, moved_at, qty_after
`

type CreateStockMovementParams struct {
	ItemID       int64          `json:"item_id"`
	LocationID   int64          `json:"location_id"`
	BatchID      pgtype.Int8    `json:"batch_id"`
	Status       interface{}    `json:"status"`
	MovementType interface{}    `json:"movement_type"`
	Qty          pgtype.Numeric `json:"qty"`
	QtyAfter     pgtype.Numeric `json:"qty_after"`
	DocLineID    int64          `json:"doc_line_id"`
	DocNo        string         `json:"doc_no"`
	CreatedBy    int64          `json:"created_by"`
}

type CreateStockMovementRow struct {
	ID       int64              `json:"id"`
	MovedAt  pgtype.Timestamptz `json:"moved_at"`
	QtyAfter pgtype.Numeric     `json:"qty_after"`
}

func (q *Queries) CreateStockMovement(ctx context.Context, arg CreateStockMovementParams) (CreateStockMovementRow, error) {
	row := q.db.QueryRow(ctx, createStockMovement,
		arg.ItemID,
		arg.LocationID,
		arg.BatchID,
		arg.Status,
		arg.MovementType,
		arg.Qty,
		arg.QtyAfter,
		arg.DocLineID,
		arg.DocNo,
		arg.CreatedBy,
	)
	var i CreateStockMovementRow
	err := row.Scan(&i.ID, &i.MovedAt, &i.QtyAfter)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO sec.users (username, email, full_name, password_hash, is_active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, email, full_name, is_active
`

type CreateUserParams struct {
	Username     string      `json:"username"`
	Email        pgtype.Text `json:"email"`
	FullName     string      `json:"full_name"`
	PasswordHash string      `json:"password_hash"`
	IsActive     bool        `json:"is_active"`
}

type CreateUserRow struct {
	ID       int64       `json:"id"`
	Username string      `json:"username"`
	Email    pgtype.Text `json:"email"`
	FullName string      `json:"full_name"`
	IsActive bool        `json:"is_active"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.FullName,
		arg.PasswordHash,
		arg.IsActive,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.IsActive,
	)
	return i, err
}

const createWarehouse = `-- name: CreateWarehouse :one
INSERT INTO master.warehouses (code, name, address, is_active)
VALUES ($1, $2, $3, $4)
RETURNING id, code, name, address, is_active
`

type CreateWarehouseParams struct {
	Code     string      `json:"code"`
	Name     string      `json:"name"`
	Address  pgtype.Text `json:"address"`
	IsActive bool        `json:"is_active"`
}

func (q *Queries) CreateWarehouse(ctx context.Context, arg CreateWarehouseParams) (MasterWarehouses, error) {
	row := q.db.QueryRow(ctx, createWarehouse,
		arg.Code,
		arg.Name,
		arg.Address,
		arg.IsActive,
	)
	var i MasterWarehouses
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Address,
		&i.IsActive,
	)
	return i, err
}

const deleteItemUoMs = `-- name: DeleteItemUoMs :exec
DELETE FROM master.item_uoms
WHERE item_id = $1
`

func (q *Queries) DeleteItemUoMs(ctx context.Context, itemID int64) error {
	_, err := q.db.Exec(ctx, deleteItemUoMs, itemID)
	return err
}

const deleteLocation = `-- name: DeleteLocation :exec
DELETE FROM master.locations
WHERE id = $1
`

func (q *Queries) DeleteLocation(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteLocation, id)
	return err
}

const deletePartner = `-- name: DeletePartner :exec
DELETE FROM master.partners
WHERE id = $1
`

func (q *Queries) DeletePartner(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePartner, id)
	return err
}

const getItemByID = `-- name: GetItemByID :one
SELECT id, public_id, sku, name, category_id, base_uom, is_batch, is_expiry, is_serial, min_qty, max_qty, safety_stock, lead_time_days, abc_class, is_active, created_at, created_by, updated_at, updated_by
FROM master.items
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetItemByID(ctx context.Context, id int64) (MasterItems, error) {
	row := q.db.QueryRow(ctx, getItemByID, id)
	var i MasterItems
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Sku,
		&i.Name,
		&i.CategoryID,
		&i.BaseUom,
		&i.IsBatch,
		&i.IsExpiry,
		&i.IsSerial,
		&i.MinQty,
		&i.MaxQty,
		&i.SafetyStock,
		&i.LeadTimeDays,
		&i.AbcClass,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getItemBySKU = `-- name: GetItemBySKU :one
SELECT id, public_id, sku, name, category_id, base_uom, is_batch, is_expiry, is_serial, min_qty, max_qty, safety_stock, lead_time_days, abc_class, is_active, created_at, created_by
FROM master.items
WHERE sku = $1 LIMIT 1
`

type GetItemBySKURow struct {
	ID           int64              `json:"id"`
	PublicID     pgtype.UUID        `json:"public_id"`
	Sku          string             `json:"sku"`
	Name         string             `json:"name"`
	CategoryID   pgtype.Int8        `json:"category_id"`
	BaseUom      string             `json:"base_uom"`
	IsBatch      bool               `json:"is_batch"`
	IsExpiry     bool               `json:"is_expiry"`
	IsSerial     bool               `json:"is_serial"`
	MinQty       pgtype.Numeric     `json:"min_qty"`
	MaxQty       pgtype.Numeric     `json:"max_qty"`
	SafetyStock  pgtype.Numeric     `json:"safety_stock"`
	LeadTimeDays int16              `json:"lead_time_days"`
	AbcClass     pgtype.Text        `json:"abc_class"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CreatedBy    int64              `json:"created_by"`
}

func (q *Queries) GetItemBySKU(ctx context.Context, sku string) (GetItemBySKURow, error) {
	row := q.db.QueryRow(ctx, getItemBySKU, sku)
	var i GetItemBySKURow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Sku,
		&i.Name,
		&i.CategoryID,
		&i.BaseUom,
		&i.IsBatch,
		&i.IsExpiry,
		&i.IsSerial,
		&i.MinQty,
		&i.MaxQty,
		&i.SafetyStock,
		&i.LeadTimeDays,
		&i.AbcClass,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getLocationByID = `-- name: GetLocationByID :one
SELECT id, warehouse_id, code, zone, rack, level, loc_type, pick_seq, capacity, is_active
FROM master.locations
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetLocationByID(ctx context.Context, id int64) (MasterLocations, error) {
	row := q.db.QueryRow(ctx, getLocationByID, id)
	var i MasterLocations
	err := row.Scan(
		&i.ID,
		&i.WarehouseID,
		&i.Code,
		&i.Zone,
		&i.Rack,
		&i.Level,
		&i.LocType,
		&i.PickSeq,
		&i.Capacity,
		&i.IsActive,
	)
	return i, err
}

const getPartnerByID = `-- name: GetPartnerByID :one
SELECT id, code, partner_type, name, address, contact_name, contact_phone, is_active
FROM master.partners
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPartnerByID(ctx context.Context, id int64) (MasterPartners, error) {
	row := q.db.QueryRow(ctx, getPartnerByID, id)
	var i MasterPartners
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.PartnerType,
		&i.Name,
		&i.Address,
		&i.ContactName,
		&i.ContactPhone,
		&i.IsActive,
	)
	return i, err
}

const getStockBalanceByIDForUpdate = `-- name: GetStockBalanceByIDForUpdate :one
SELECT id, item_id, location_id, batch_id, status, qty_onhand, qty_reserved
FROM inv.stock_balances
WHERE id = $1
FOR UPDATE
`

type GetStockBalanceByIDForUpdateRow struct {
	ID          int64          `json:"id"`
	ItemID      int64          `json:"item_id"`
	LocationID  int64          `json:"location_id"`
	BatchID     pgtype.Int8    `json:"batch_id"`
	Status      interface{}    `json:"status"`
	QtyOnhand   pgtype.Numeric `json:"qty_onhand"`
	QtyReserved pgtype.Numeric `json:"qty_reserved"`
}

func (q *Queries) GetStockBalanceByIDForUpdate(ctx context.Context, id int64) (GetStockBalanceByIDForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getStockBalanceByIDForUpdate, id)
	var i GetStockBalanceByIDForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.LocationID,
		&i.BatchID,
		&i.Status,
		&i.QtyOnhand,
		&i.QtyReserved,
	)
	return i, err
}

const getStockBalanceForUpdate = `-- name: GetStockBalanceForUpdate :one
SELECT id, item_id, location_id, batch_id, status, qty_onhand, qty_reserved, updated_at
FROM inv.stock_balances
WHERE item_id = $1 AND location_id = $2 AND COALESCE(batch_id, 0) = COALESCE($3, 0) AND status = $4
FOR UPDATE
`

type GetStockBalanceForUpdateParams struct {
	ItemID     int64       `json:"item_id"`
	LocationID int64       `json:"location_id"`
	BatchID    pgtype.Int8 `json:"batch_id"`
	Status     interface{} `json:"status"`
}

func (q *Queries) GetStockBalanceForUpdate(ctx context.Context, arg GetStockBalanceForUpdateParams) (InvStockBalances, error) {
	row := q.db.QueryRow(ctx, getStockBalanceForUpdate,
		arg.ItemID,
		arg.LocationID,
		arg.BatchID,
		arg.Status,
	)
	var i InvStockBalances
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.LocationID,
		&i.BatchID,
		&i.Status,
		&i.QtyOnhand,
		&i.QtyReserved,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, full_name, password_hash, is_active, mfa_secret, last_login_at
FROM sec.users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (SecUsers, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i SecUsers
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.IsActive,
		&i.MfaSecret,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, full_name, password_hash, is_active, mfa_secret, last_login_at
FROM sec.users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (SecUsers, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i SecUsers
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.IsActive,
		&i.MfaSecret,
		&i.LastLoginAt,
	)
	return i, err
}

const getWarehouseByCode = `-- name: GetWarehouseByCode :one
SELECT id, code, name, address, is_active FROM master.warehouses
WHERE code = $1 LIMIT 1
`

func (q *Queries) GetWarehouseByCode(ctx context.Context, code string) (MasterWarehouses, error) {
	row := q.db.QueryRow(ctx, getWarehouseByCode, code)
	var i MasterWarehouses
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Address,
		&i.IsActive,
	)
	return i, err
}

const insertStockMovement = `-- name: InsertStockMovement :exec
INSERT INTO inv.stock_movements (item_id, location_id, batch_id, status, movement_type, qty, qty_after, doc_line_id, doc_no, created_by, moved_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW())
`

type InsertStockMovementParams struct {
	ItemID       int64          `json:"item_id"`
	LocationID   int64          `json:"location_id"`
	BatchID      pgtype.Int8    `json:"batch_id"`
	Status       interface{}    `json:"status"`
	MovementType interface{}    `json:"movement_type"`
	Qty          pgtype.Numeric `json:"qty"`
	QtyAfter     pgtype.Numeric `json:"qty_after"`
	DocLineID    int64          `json:"doc_line_id"`
	DocNo        string         `json:"doc_no"`
	CreatedBy    int64          `json:"created_by"`
}

func (q *Queries) InsertStockMovement(ctx context.Context, arg InsertStockMovementParams) error {
	_, err := q.db.Exec(ctx, insertStockMovement,
		arg.ItemID,
		arg.LocationID,
		arg.BatchID,
		arg.Status,
		arg.MovementType,
		arg.Qty,
		arg.QtyAfter,
		arg.DocLineID,
		arg.DocNo,
		arg.CreatedBy,
	)
	return err
}

const listItemUoMs = `-- name: ListItemUoMs :many
SELECT id, item_id, uom, conv_factor, barcode
FROM master.item_uoms
WHERE item_id = $1
ORDER BY conv_factor
`

func (q *Queries) ListItemUoMs(ctx context.Context, itemID int64) ([]MasterItemUoms, error) {
	rows, err := q.db.Query(ctx, listItemUoMs, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MasterItemUoms
	for rows.Next() {
		var i MasterItemUoms
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.Uom,
			&i.ConvFactor,
			&i.Barcode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItems = `-- name: ListItems :many
SELECT id, public_id, sku, name, category_id, base_uom, is_batch, is_expiry, is_serial, min_qty, max_qty, safety_stock, lead_time_days, abc_class, is_active
FROM master.items
ORDER BY sku
`

type ListItemsRow struct {
	ID           int64          `json:"id"`
	PublicID     pgtype.UUID    `json:"public_id"`
	Sku          string         `json:"sku"`
	Name         string         `json:"name"`
	CategoryID   pgtype.Int8    `json:"category_id"`
	BaseUom      string         `json:"base_uom"`
	IsBatch      bool           `json:"is_batch"`
	IsExpiry     bool           `json:"is_expiry"`
	IsSerial     bool           `json:"is_serial"`
	MinQty       pgtype.Numeric `json:"min_qty"`
	MaxQty       pgtype.Numeric `json:"max_qty"`
	SafetyStock  pgtype.Numeric `json:"safety_stock"`
	LeadTimeDays int16          `json:"lead_time_days"`
	AbcClass     pgtype.Text    `json:"abc_class"`
	IsActive     bool           `json:"is_active"`
}

func (q *Queries) ListItems(ctx context.Context) ([]ListItemsRow, error) {
	rows, err := q.db.Query(ctx, listItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemsRow
	for rows.Next() {
		var i ListItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Sku,
			&i.Name,
			&i.CategoryID,
			&i.BaseUom,
			&i.IsBatch,
			&i.IsExpiry,
			&i.IsSerial,
			&i.MinQty,
			&i.MaxQty,
			&i.SafetyStock,
			&i.LeadTimeDays,
			&i.AbcClass,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocations = `-- name: ListLocations :many
SELECT id, warehouse_id, code, zone, rack, level, loc_type, pick_seq, capacity, is_active
FROM master.locations
WHERE warehouse_id = $1
ORDER BY code
`

func (q *Queries) ListLocations(ctx context.Context, warehouseID int64) ([]MasterLocations, error) {
	rows, err := q.db.Query(ctx, listLocations, warehouseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MasterLocations
	for rows.Next() {
		var i MasterLocations
		if err := rows.Scan(
			&i.ID,
			&i.WarehouseID,
			&i.Code,
			&i.Zone,
			&i.Rack,
			&i.Level,
			&i.LocType,
			&i.PickSeq,
			&i.Capacity,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartners = `-- name: ListPartners :many
SELECT id, code, partner_type, name, address, contact_name, contact_phone, is_active
FROM master.partners
ORDER BY code
`

func (q *Queries) ListPartners(ctx context.Context) ([]MasterPartners, error) {
	rows, err := q.db.Query(ctx, listPartners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MasterPartners
	for rows.Next() {
		var i MasterPartners
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.PartnerType,
			&i.Name,
			&i.Address,
			&i.ContactName,
			&i.ContactPhone,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolePermissions = `-- name: ListRolePermissions :many

SELECT r.code AS role_code, p.code AS permission_code
FROM sec.roles r
JOIN sec.role_permissions rp ON rp.role_id = r.id
JOIN sec.permissions p ON p.id = rp.permission_id
ORDER BY r.code, p.code
`

type ListRolePermissionsRow struct {
	RoleCode       pgtype.Text `json:"role_code"`
	PermissionCode pgtype.Text `json:"permission_code"`
}

// ============ RBAC (Fase 2.4) ============
func (q *Queries) ListRolePermissions(ctx context.Context) ([]ListRolePermissionsRow, error) {
	rows, err := q.db.Query(ctx, listRolePermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRolePermissionsRow
	for rows.Next() {
		var i ListRolePermissionsRow
		if err := rows.Scan(&i.RoleCode, &i.PermissionCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockMovementsKeyset = `-- name: ListStockMovementsKeyset :many
SELECT id, moved_at, item_id, location_id, batch_id, status, movement_type, qty, qty_after, doc_line_id, doc_no, created_by
FROM inv.stock_movements
WHERE moved_at >= $1 AND moved_at <= $2
  AND ($3::bigint = 0 OR item_id = $3)
  AND ($4::bigint = 0 OR location_id = $4)
  AND ($5::boolean = FALSE OR (moved_at < $6::timestamptz OR (moved_at = $6::timestamptz AND id < $7::bigint)))
ORDER BY moved_at DESC, id DESC
LIMIT $8
`

type ListStockMovementsKeysetParams struct {
	MovedAt   pgtype.Timestamptz `json:"moved_at"`
	MovedAt_2 pgtype.Timestamptz `json:"moved_at_2"`
	Column3   int64              `json:"column_3"`
	Column4   int64              `json:"column_4"`
	Column5   bool               `json:"column_5"`
	Column6   pgtype.Timestamptz `json:"column_6"`
	Column7   int64              `json:"column_7"`
	Limit     int32              `json:"limit"`
}

type ListStockMovementsKeysetRow struct {
	ID           int64              `json:"id"`
	MovedAt      pgtype.Timestamptz `json:"moved_at"`
	ItemID       int64              `json:"item_id"`
	LocationID   int64              `json:"location_id"`
	BatchID      pgtype.Int8        `json:"batch_id"`
	Status       interface{}        `json:"status"`
	MovementType interface{}        `json:"movement_type"`
	Qty          pgtype.Numeric     `json:"qty"`
	QtyAfter     pgtype.Numeric     `json:"qty_after"`
	DocLineID    int64              `json:"doc_line_id"`
	DocNo        string             `json:"doc_no"`
	CreatedBy    int64              `json:"created_by"`
}

func (q *Queries) ListStockMovementsKeyset(ctx context.Context, arg ListStockMovementsKeysetParams) ([]ListStockMovementsKeysetRow, error) {
	rows, err := q.db.Query(ctx, listStockMovementsKeyset,
		arg.MovedAt,
		arg.MovedAt_2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStockMovementsKeysetRow
	for rows.Next() {
		var i ListStockMovementsKeysetRow
		if err := rows.Scan(
			&i.ID,
			&i.MovedAt,
			&i.ItemID,
			&i.LocationID,
			&i.BatchID,
			&i.Status,
			&i.MovementType,
			&i.Qty,
			&i.QtyAfter,
			&i.DocLineID,
			&i.DocNo,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoleCodes = `-- name: ListUserRoleCodes :many
SELECT DISTINCT COALESCE(r.code, '') AS code
FROM sec.roles r
JOIN sec.user_roles ur ON ur.role_id = r.id
WHERE ur.user_id = $1
ORDER BY code
`

func (q *Queries) ListUserRoleCodes(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserRoleCodes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserWarehouseCodes = `-- name: ListUserWarehouseCodes :many
SELECT DISTINCT w.code
FROM master.warehouses w
JOIN sec.user_roles ur ON ur.warehouse_id = w.id
WHERE ur.user_id = $1
ORDER BY w.code
`

func (q *Queries) ListUserWarehouseCodes(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserWarehouseCodes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWarehouseCodes = `-- name: ListWarehouseCodes :many
SELECT code FROM master.warehouses WHERE is_active = TRUE ORDER BY code
`

func (q *Queries) ListWarehouseCodes(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listWarehouseCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWarehouses = `-- name: ListWarehouses :many
SELECT id, code, name, address, is_active FROM master.warehouses
ORDER BY code
`

func (q *Queries) ListWarehouses(ctx context.Context) ([]MasterWarehouses, error) {
	rows, err := q.db.Query(ctx, listWarehouses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MasterWarehouses
	for rows.Next() {
		var i MasterWarehouses
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Address,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteItem = `-- name: SoftDeleteItem :one
UPDATE master.items
SET is_active = FALSE, updated_at = NOW(), updated_by = $2
WHERE id = $1
RETURNING id, is_active
`

type SoftDeleteItemParams struct {
	ID        int64       `json:"id"`
	UpdatedBy pgtype.Int8 `json:"updated_by"`
}

type SoftDeleteItemRow struct {
	ID       int64 `json:"id"`
	IsActive bool  `json:"is_active"`
}

func (q *Queries) SoftDeleteItem(ctx context.Context, arg SoftDeleteItemParams) (SoftDeleteItemRow, error) {
	row := q.db.QueryRow(ctx, softDeleteItem, arg.ID, arg.UpdatedBy)
	var i SoftDeleteItemRow
	err := row.Scan(&i.ID, &i.IsActive)
	return i, err
}

const updateItem = `-- name: UpdateItem :one
UPDATE master.items
SET name = $2, category_id = $3, base_uom = $4, is_batch = $5, is_expiry = $6, is_serial = $7,
    min_qty = $8, max_qty = $9, safety_stock = $10, lead_time_days = $11, abc_class = $12, is_active = $13,
    updated_at = NOW(), updated_by = $14
WHERE id = $1
RETURNING id, public_id, sku, name, category_id, base_uom, is_batch, is_expiry, is_serial, min_qty, max_qty, safety_stock, lead_time_days, abc_class, is_active, updated_at, updated_by
`

type UpdateItemParams struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	CategoryID   pgtype.Int8    `json:"category_id"`
	BaseUom      string         `json:"base_uom"`
	IsBatch      bool           `json:"is_batch"`
	IsExpiry     bool           `json:"is_expiry"`
	IsSerial     bool           `json:"is_serial"`
	MinQty       pgtype.Numeric `json:"min_qty"`
	MaxQty       pgtype.Numeric `json:"max_qty"`
	SafetyStock  pgtype.Numeric `json:"safety_stock"`
	LeadTimeDays int16          `json:"lead_time_days"`
	AbcClass     pgtype.Text    `json:"abc_class"`
	IsActive     bool           `json:"is_active"`
	UpdatedBy    pgtype.Int8    `json:"updated_by"`
}

type UpdateItemRow struct {
	ID           int64              `json:"id"`
	PublicID     pgtype.UUID        `json:"public_id"`
	Sku          string             `json:"sku"`
	Name         string             `json:"name"`
	CategoryID   pgtype.Int8        `json:"category_id"`
	BaseUom      string             `json:"base_uom"`
	IsBatch      bool               `json:"is_batch"`
	IsExpiry     bool               `json:"is_expiry"`
	IsSerial     bool               `json:"is_serial"`
	MinQty       pgtype.Numeric     `json:"min_qty"`
	MaxQty       pgtype.Numeric     `json:"max_qty"`
	SafetyStock  pgtype.Numeric     `json:"safety_stock"`
	LeadTimeDays int16              `json:"lead_time_days"`
	AbcClass     pgtype.Text        `json:"abc_class"`
	IsActive     bool               `json:"is_active"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy    pgtype.Int8        `json:"updated_by"`
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (UpdateItemRow, error) {
	row := q.db.QueryRow(ctx, updateItem,
		arg.ID,
		arg.Name,
		arg.CategoryID,
		arg.BaseUom,
		arg.IsBatch,
		arg.IsExpiry,
		arg.IsSerial,
		arg.MinQty,
		arg.MaxQty,
		arg.SafetyStock,
		arg.LeadTimeDays,
		arg.AbcClass,
		arg.IsActive,
		arg.UpdatedBy,
	)
	var i UpdateItemRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Sku,
		&i.Name,
		&i.CategoryID,
		&i.BaseUom,
		&i.IsBatch,
		&i.IsExpiry,
		&i.IsSerial,
		&i.MinQty,
		&i.MaxQty,
		&i.SafetyStock,
		&i.LeadTimeDays,
		&i.AbcClass,
		&i.IsActive,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const updateLocation = `-- name: UpdateLocation :one
UPDATE master.locations
SET code = $2, zone = $3, rack = $4, level = $5, loc_type = $6, pick_seq = $7, capacity = $8, is_active = $9
WHERE id = $1
RETURNING id, warehouse_id, code, zone, rack, level, loc_type, pick_seq, capacity, is_active
`

type UpdateLocationParams struct {
	ID       int64          `json:"id"`
	Code     string         `json:"code"`
	Zone     pgtype.Text    `json:"zone"`
	Rack     pgtype.Text    `json:"rack"`
	Level    pgtype.Text    `json:"level"`
	LocType  interface{}    `json:"loc_type"`
	PickSeq  pgtype.Int4    `json:"pick_seq"`
	Capacity pgtype.Numeric `json:"capacity"`
	IsActive bool           `json:"is_active"`
}

func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) (MasterLocations, error) {
	row := q.db.QueryRow(ctx, updateLocation,
		arg.ID,
		arg.Code,
		arg.Zone,
		arg.Rack,
		arg.Level,
		arg.LocType,
		arg.PickSeq,
		arg.Capacity,
		arg.IsActive,
	)
	var i MasterLocations
	err := row.Scan(
		&i.ID,
		&i.WarehouseID,
		&i.Code,
		&i.Zone,
		&i.Rack,
		&i.Level,
		&i.LocType,
		&i.PickSeq,
		&i.Capacity,
		&i.IsActive,
	)
	return i, err
}

const updatePartner = `-- name: UpdatePartner :one
UPDATE master.partners
SET code = $2, partner_type = $3, name = $4, address = $5, contact_name = $6, contact_phone = $7, is_active = $8
WHERE id = $1
RETURNING id, code, partner_type, name, address, contact_name, contact_phone, is_active
`

type UpdatePartnerParams struct {
	ID           int64       `json:"id"`
	Code         string      `json:"code"`
	PartnerType  string      `json:"partner_type"`
	Name         string      `json:"name"`
	Address      pgtype.Text `json:"address"`
	ContactName  pgtype.Text `json:"contact_name"`
	ContactPhone pgtype.Text `json:"contact_phone"`
	IsActive     bool        `json:"is_active"`
}

func (q *Queries) UpdatePartner(ctx context.Context, arg UpdatePartnerParams) (MasterPartners, error) {
	row := q.db.QueryRow(ctx, updatePartner,
		arg.ID,
		arg.Code,
		arg.PartnerType,
		arg.Name,
		arg.Address,
		arg.ContactName,
		arg.ContactPhone,
		arg.IsActive,
	)
	var i MasterPartners
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.PartnerType,
		&i.Name,
		&i.Address,
		&i.ContactName,
		&i.ContactPhone,
		&i.IsActive,
	)
	return i, err
}

const updateStockBalanceQty = `-- name: UpdateStockBalanceQty :one
UPDATE inv.stock_balances
SET qty_onhand = $2, qty_reserved = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, qty_onhand, qty_reserved
`

type UpdateStockBalanceQtyParams struct {
	ID          int64          `json:"id"`
	QtyOnhand   pgtype.Numeric `json:"qty_onhand"`
	QtyReserved pgtype.Numeric `json:"qty_reserved"`
}

type UpdateStockBalanceQtyRow struct {
	ID          int64          `json:"id"`
	QtyOnhand   pgtype.Numeric `json:"qty_onhand"`
	QtyReserved pgtype.Numeric `json:"qty_reserved"`
}

func (q *Queries) UpdateStockBalanceQty(ctx context.Context, arg UpdateStockBalanceQtyParams) (UpdateStockBalanceQtyRow, error) {
	row := q.db.QueryRow(ctx, updateStockBalanceQty, arg.ID, arg.QtyOnhand, arg.QtyReserved)
	var i UpdateStockBalanceQtyRow
	err := row.Scan(&i.ID, &i.QtyOnhand, &i.QtyReserved)
	return i, err
}

const upsertDocumentNumber = `-- name: UpsertDocumentNumber :one

INSERT INTO doc.document_numbers (doc_type, period, last_seq)
VALUES ($1, $2, 1)
ON CONFLICT (doc_type, period)
DO UPDATE SET last_seq = doc.document_numbers.last_seq + 1
RETURNING last_seq
`

type UpsertDocumentNumberParams struct {
	DocType interface{} `json:"doc_type"`
	Period  string      `json:"period"`
}

// ============ Dokumen (Fase 5.1 - BR-04) ============
// Atomic sequence bump: returns the next sequence for (doc_type, period).
// Must run inside the same transaction that creates the document (FSD 4.3).
// Period is computed by the application from the same clock as the document
// number so the sequence and the formatted number can never diverge.
func (q *Queries) UpsertDocumentNumber(ctx context.Context, arg UpsertDocumentNumberParams) (int32, error) {
	row := q.db.QueryRow(ctx, upsertDocumentNumber, arg.DocType, arg.Period)
	var last_seq int32
	err := row.Scan(&last_seq)
	return last_seq, err
}

const upsertStockBalance = `-- name: UpsertStockBalance :one

INSERT INTO inv.stock_balances (item_id, location_id, batch_id, status, qty_onhand, qty_reserved, updated_at)
VALUES ($1, $2, $3, $4, 0, 0, NOW())
ON CONFLICT (item_id, location_id, COALESCE(batch_id, 0), status) DO UPDATE SET updated_at = NOW()
RETURNING id, qty_onhand, qty_reserved
`

type UpsertStockBalanceParams struct {
	ItemID     int64       `json:"item_id"`
	LocationID int64       `json:"location_id"`
	BatchID    pgtype.Int8 `json:"batch_id"`
	Status     interface{} `json:"status"`
}

type UpsertStockBalanceRow struct {
	ID          int64          `json:"id"`
	QtyOnhand   pgtype.Numeric `json:"qty_onhand"`
	QtyReserved pgtype.Numeric `json:"qty_reserved"`
}

// ============ STOCK BALANCES & MOVEMENTS ============
func (q *Queries) UpsertStockBalance(ctx context.Context, arg UpsertStockBalanceParams) (UpsertStockBalanceRow, error) {
	row := q.db.QueryRow(ctx, upsertStockBalance,
		arg.ItemID,
		arg.LocationID,
		arg.BatchID,
		arg.Status,
	)
	var i UpsertStockBalanceRow
	err := row.Scan(&i.ID, &i.QtyOnhand, &i.QtyReserved)
	return i, err
}

const upsertStockBalanceFull = `-- name: UpsertStockBalanceFull :exec
INSERT INTO inv.stock_balances (item_id, location_id, batch_id, status, qty_onhand, qty_reserved, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
ON CONFLICT (item_id, location_id, COALESCE(batch_id, 0), status)
DO UPDATE SET qty_onhand = EXCLUDED.qty_onhand, qty_reserved = EXCLUDED.qty_reserved, updated_at = NOW()
`

type UpsertStockBalanceFullParams struct {
	ItemID      int64          `json:"item_id"`
	LocationID  int64          `json:"location_id"`
	BatchID     pgtype.Int8    `json:"batch_id"`
	Status      interface{}    `json:"status"`
	QtyOnhand   pgtype.Numeric `json:"qty_onhand"`
	QtyReserved pgtype.Numeric `json:"qty_reserved"`
}

func (q *Queries) UpsertStockBalanceFull(ctx context.Context, arg UpsertStockBalanceFullParams) error {
	_, err := q.db.Exec(ctx, upsertStockBalanceFull,
		arg.ItemID,
		arg.LocationID,
		arg.BatchID,
		arg.Status,
		arg.QtyOnhand,
		arg.QtyReserved,
	)
	return err
}
