// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
)

type Querier interface {
	// ============ CATEGORIES ============
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (MasterCategories, error)
	// ============ ITEMS & UOMS ============
	CreateItem(ctx context.Context, arg CreateItemParams) (CreateItemRow, error)
	CreateItemUoM(ctx context.Context, arg CreateItemUoMParams) (MasterItemUoms, error)
	// ============ LOCATIONS ============
	CreateLocation(ctx context.Context, arg CreateLocationParams) (MasterLocations, error)
	// ============ PARTNERS ============
	CreatePartner(ctx context.Context, arg CreatePartnerParams) (MasterPartners, error)
	CreateStockMovement(ctx context.Context, arg CreateStockMovementParams) (CreateStockMovementRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	CreateWarehouse(ctx context.Context, arg CreateWarehouseParams) (MasterWarehouses, error)
	DeleteItemUoMs(ctx context.Context, itemID int64) error
	DeleteLocation(ctx context.Context, id int64) error
	DeletePartner(ctx context.Context, id int64) error
	GetItemByID(ctx context.Context, id int64) (MasterItems, error)
	GetItemBySKU(ctx context.Context, sku string) (GetItemBySKURow, error)
	GetLocationByID(ctx context.Context, id int64) (MasterLocations, error)
	GetPartnerByID(ctx context.Context, id int64) (MasterPartners, error)
	GetStockBalanceByIDForUpdate(ctx context.Context, id int64) (GetStockBalanceByIDForUpdateRow, error)
	GetStockBalanceForUpdate(ctx context.Context, arg GetStockBalanceForUpdateParams) (InvStockBalances, error)
	GetUserByID(ctx context.Context, id int64) (SecUsers, error)
	GetUserByUsername(ctx context.Context, username string) (SecUsers, error)
	GetWarehouseByCode(ctx context.Context, code string) (MasterWarehouses, error)
	InsertStockMovement(ctx context.Context, arg InsertStockMovementParams) error
	ListItemUoMs(ctx context.Context, itemID int64) ([]MasterItemUoms, error)
	ListItems(ctx context.Context) ([]ListItemsRow, error)
	ListLocations(ctx context.Context, warehouseID int64) ([]MasterLocations, error)
	ListPartners(ctx context.Context) ([]MasterPartners, error)
	// ============ RBAC (Fase 2.4) ============
	ListRolePermissions(ctx context.Context) ([]ListRolePermissionsRow, error)
	ListStockMovementsKeyset(ctx context.Context, arg ListStockMovementsKeysetParams) ([]ListStockMovementsKeysetRow, error)
	ListUserRoleCodes(ctx context.Context, userID int64) ([]string, error)
	ListUserWarehouseCodes(ctx context.Context, userID int64) ([]string, error)
	ListWarehouseCodes(ctx context.Context) ([]string, error)
	ListWarehouses(ctx context.Context) ([]MasterWarehouses, error)
	SoftDeleteItem(ctx context.Context, arg SoftDeleteItemParams) (SoftDeleteItemRow, error)
	UpdateItem(ctx context.Context, arg UpdateItemParams) (UpdateItemRow, error)
	UpdateLocation(ctx context.Context, arg UpdateLocationParams) (MasterLocations, error)
	UpdatePartner(ctx context.Context, arg UpdatePartnerParams) (MasterPartners, error)
	UpdateStockBalanceQty(ctx context.Context, arg UpdateStockBalanceQtyParams) (UpdateStockBalanceQtyRow, error)
	// ============ STOCK BALANCES & MOVEMENTS ============
	UpsertStockBalance(ctx context.Context, arg UpsertStockBalanceParams) (UpsertStockBalanceRow, error)
	UpsertStockBalanceFull(ctx context.Context, arg UpsertStockBalanceFullParams) error
}

var _ Querier = (*Queries)(nil)
